<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 9 Binary Logistic Regression | Data Analysis in Medicine and Health using R</title>
  <meta name="description" content="Chapter 9 Binary Logistic Regression | Data Analysis in Medicine and Health using R" />
  <meta name="generator" content="bookdown 0.24 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 9 Binary Logistic Regression | Data Analysis in Medicine and Health using R" />
  <meta property="og:type" content="book" />
  <meta property="og:url" content="https://bookdown.org/drki_musa/dataanalysis/" />
  
  
  <meta name="github-repo" content="drkamarul/multivar_data_analysis" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 9 Binary Logistic Regression | Data Analysis in Medicine and Health using R" />
  
  
  

<meta name="author" content="Kamarul Imran, Wan Nor Arifin, Tengku Muhammad Hanis Tengku Mukhtar" />


<meta name="date" content="2022-01-11" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="linear-regression.html"/>
<link rel="next" href="poisson-regression.html"/>
<script src="libs/header-attrs-2.11/header-attrs.js"></script>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="css/style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Data Analysis in Medicine and Health using R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="1" data-path="introduction-to-r-rstudio-and-rstudio-cloud.html"><a href="introduction-to-r-rstudio-and-rstudio-cloud.html"><i class="fa fa-check"></i><b>1</b> Introduction to R, RStudio and RStudio Cloud</a>
<ul>
<li class="chapter" data-level="1.1" data-path="introduction-to-r-rstudio-and-rstudio-cloud.html"><a href="introduction-to-r-rstudio-and-rstudio-cloud.html#rstudio-cloud"><i class="fa fa-check"></i><b>1.1</b> RStudio Cloud</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="introduction-to-r-rstudio-and-rstudio-cloud.html"><a href="introduction-to-r-rstudio-and-rstudio-cloud.html#the-rstudio-cloud-registration"><i class="fa fa-check"></i><b>1.1.1</b> The RStudio Cloud Registration</a></li>
<li class="chapter" data-level="1.1.2" data-path="introduction-to-r-rstudio-and-rstudio-cloud.html"><a href="introduction-to-r-rstudio-and-rstudio-cloud.html#register-and-log-in"><i class="fa fa-check"></i><b>1.1.2</b> Register and log in</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="introduction-to-r-rstudio-and-rstudio-cloud.html"><a href="introduction-to-r-rstudio-and-rstudio-cloud.html#point-and-click-r-gui"><i class="fa fa-check"></i><b>1.2</b> Point and click R GUI</a></li>
<li class="chapter" data-level="1.3" data-path="introduction-to-r-rstudio-and-rstudio-cloud.html"><a href="introduction-to-r-rstudio-and-rstudio-cloud.html#rstudio-server"><i class="fa fa-check"></i><b>1.3</b> RStudio Server</a></li>
<li class="chapter" data-level="1.4" data-path="introduction-to-r-rstudio-and-rstudio-cloud.html"><a href="introduction-to-r-rstudio-and-rstudio-cloud.html#installing-r-and-rstudio-on-your-local-machine"><i class="fa fa-check"></i><b>1.4</b> Installing R and RStudio on Your Local Machine</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="introduction-to-r-rstudio-and-rstudio-cloud.html"><a href="introduction-to-r-rstudio-and-rstudio-cloud.html#installing-r"><i class="fa fa-check"></i><b>1.4.1</b> Installing R</a></li>
<li class="chapter" data-level="1.4.2" data-path="introduction-to-r-rstudio-and-rstudio-cloud.html"><a href="introduction-to-r-rstudio-and-rstudio-cloud.html#installing-rstudio-ide"><i class="fa fa-check"></i><b>1.4.2</b> Installing RStudio IDE</a></li>
<li class="chapter" data-level="1.4.3" data-path="introduction-to-r-rstudio-and-rstudio-cloud.html"><a href="introduction-to-r-rstudio-and-rstudio-cloud.html#checking-r-and-rstudio-installations"><i class="fa fa-check"></i><b>1.4.3</b> Checking R and RStudio Installations</a></li>
<li class="chapter" data-level="1.4.4" data-path="introduction-to-r-rstudio-and-rstudio-cloud.html"><a href="introduction-to-r-rstudio-and-rstudio-cloud.html#installation-of-miktex-texlive-and-mactex"><i class="fa fa-check"></i><b>1.4.4</b> Installation of MiKTeX, TeXLive and MacTex</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="introduction-to-r-rstudio-and-rstudio-cloud.html"><a href="introduction-to-r-rstudio-and-rstudio-cloud.html#starting-your-rstudio"><i class="fa fa-check"></i><b>1.5</b> Starting your RStudio</a>
<ul>
<li class="chapter" data-level="1.5.1" data-path="introduction-to-r-rstudio-and-rstudio-cloud.html"><a href="introduction-to-r-rstudio-and-rstudio-cloud.html#console-tab"><i class="fa fa-check"></i><b>1.5.1</b> Console tab</a></li>
<li class="chapter" data-level="1.5.2" data-path="introduction-to-r-rstudio-and-rstudio-cloud.html"><a href="introduction-to-r-rstudio-and-rstudio-cloud.html#files-plots-packages-help-and-viewer-pane"><i class="fa fa-check"></i><b>1.5.2</b> Files, Plots, Packages, Help and Viewer Pane</a></li>
<li class="chapter" data-level="1.5.3" data-path="introduction-to-r-rstudio-and-rstudio-cloud.html"><a href="introduction-to-r-rstudio-and-rstudio-cloud.html#environment-history-connection-and-build-pane"><i class="fa fa-check"></i><b>1.5.3</b> Environment, History, Connection and Build Pane</a></li>
<li class="chapter" data-level="1.5.4" data-path="introduction-to-r-rstudio-and-rstudio-cloud.html"><a href="introduction-to-r-rstudio-and-rstudio-cloud.html#source-pane"><i class="fa fa-check"></i><b>1.5.4</b> Source Pane</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="r-scripts-and-r-packages.html"><a href="r-scripts-and-r-packages.html"><i class="fa fa-check"></i><b>2</b> R Scripts and R Packages</a>
<ul>
<li class="chapter" data-level="2.1" data-path="r-scripts-and-r-packages.html"><a href="r-scripts-and-r-packages.html#open-a-new-r-script"><i class="fa fa-check"></i><b>2.1</b> Open a new R script</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="r-scripts-and-r-packages.html"><a href="r-scripts-and-r-packages.html#our-first-r-script"><i class="fa fa-check"></i><b>2.1.1</b> Our first R script</a></li>
<li class="chapter" data-level="2.1.2" data-path="r-scripts-and-r-packages.html"><a href="r-scripts-and-r-packages.html#function-argument-and-parameters"><i class="fa fa-check"></i><b>2.1.2</b> Function, Argument and Parameters</a></li>
<li class="chapter" data-level="2.1.3" data-path="r-scripts-and-r-packages.html"><a href="r-scripts-and-r-packages.html#need-more-help"><i class="fa fa-check"></i><b>2.1.3</b> Need more help?</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="r-scripts-and-r-packages.html"><a href="r-scripts-and-r-packages.html#packages"><i class="fa fa-check"></i><b>2.2</b> Packages</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="r-scripts-and-r-packages.html"><a href="r-scripts-and-r-packages.html#packages-on-cran"><i class="fa fa-check"></i><b>2.2.1</b> Packages on CRAN</a></li>
<li class="chapter" data-level="2.2.2" data-path="r-scripts-and-r-packages.html"><a href="r-scripts-and-r-packages.html#check-if-the-package-you-need-is-available-in-your-r-library"><i class="fa fa-check"></i><b>2.2.2</b> Check if the package you need is available in your R library</a></li>
<li class="chapter" data-level="2.2.3" data-path="r-scripts-and-r-packages.html"><a href="r-scripts-and-r-packages.html#install-an-r-package"><i class="fa fa-check"></i><b>2.2.3</b> Install an R package</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="r-scripts-and-r-packages.html"><a href="r-scripts-and-r-packages.html#directory"><i class="fa fa-check"></i><b>2.3</b> Directory</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="r-scripts-and-r-packages.html"><a href="r-scripts-and-r-packages.html#starting-your-r-job"><i class="fa fa-check"></i><b>2.3.1</b> Starting your R job</a></li>
<li class="chapter" data-level="2.3.2" data-path="r-scripts-and-r-packages.html"><a href="r-scripts-and-r-packages.html#create-new-project"><i class="fa fa-check"></i><b>2.3.2</b> Create new project</a></li>
<li class="chapter" data-level="2.3.3" data-path="r-scripts-and-r-packages.html"><a href="r-scripts-and-r-packages.html#where-is-my-data"><i class="fa fa-check"></i><b>2.3.3</b> Where is my data?</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="r-scripts-and-r-packages.html"><a href="r-scripts-and-r-packages.html#upload-data-to-rstudio-cloud"><i class="fa fa-check"></i><b>2.4</b> Upload data to RStudio Cloud</a></li>
<li class="chapter" data-level="2.5" data-path="r-scripts-and-r-packages.html"><a href="r-scripts-and-r-packages.html#more-resources-on-rstudio-cloud"><i class="fa fa-check"></i><b>2.5</b> More resources on RStudio Cloud</a></li>
<li class="chapter" data-level="2.6" data-path="r-scripts-and-r-packages.html"><a href="r-scripts-and-r-packages.html#need-help"><i class="fa fa-check"></i><b>2.6</b> Need help?</a></li>
<li class="chapter" data-level="2.7" data-path="r-scripts-and-r-packages.html"><a href="r-scripts-and-r-packages.html#bookdown"><i class="fa fa-check"></i><b>2.7</b> Bookdown</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="rstudio-project.html"><a href="rstudio-project.html"><i class="fa fa-check"></i><b>3</b> RStudio Project</a>
<ul>
<li class="chapter" data-level="3.1" data-path="rstudio-project.html"><a href="rstudio-project.html#objectives"><i class="fa fa-check"></i><b>3.1</b> Objectives</a></li>
<li class="chapter" data-level="3.2" data-path="rstudio-project.html"><a href="rstudio-project.html#dataset-repository-on-github"><i class="fa fa-check"></i><b>3.2</b> Dataset repository on GitHub</a></li>
<li class="chapter" data-level="3.3" data-path="rstudio-project.html"><a href="rstudio-project.html#rstudio-project-on-rstudio-cloud"><i class="fa fa-check"></i><b>3.3</b> RStudio project on RStudio Cloud</a></li>
<li class="chapter" data-level="3.4" data-path="rstudio-project.html"><a href="rstudio-project.html#rstudio-project-on-local-machine"><i class="fa fa-check"></i><b>3.4</b> RStudio project on local machine</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="data-visualization.html"><a href="data-visualization.html"><i class="fa fa-check"></i><b>4</b> Data Visualization</a>
<ul>
<li class="chapter" data-level="4.1" data-path="data-visualization.html"><a href="data-visualization.html#introduction"><i class="fa fa-check"></i><b>4.1</b> Introduction</a></li>
<li class="chapter" data-level="4.2" data-path="data-visualization.html"><a href="data-visualization.html#history-and-objectives-of-data-visualization"><i class="fa fa-check"></i><b>4.2</b> History and objectives of Data Visualization</a></li>
<li class="chapter" data-level="4.3" data-path="data-visualization.html"><a href="data-visualization.html#ingredients-for-good-graphics"><i class="fa fa-check"></i><b>4.3</b> Ingredients for Good Graphics</a></li>
<li class="chapter" data-level="4.4" data-path="data-visualization.html"><a href="data-visualization.html#graphics-packages-in-r"><i class="fa fa-check"></i><b>4.4</b> Graphics Packages in R</a></li>
<li class="chapter" data-level="4.5" data-path="data-visualization.html"><a href="data-visualization.html#the-ggplot2-package"><i class="fa fa-check"></i><b>4.5</b> The <strong>ggplot2</strong> Package</a></li>
<li class="chapter" data-level="4.6" data-path="data-visualization.html"><a href="data-visualization.html#preparation"><i class="fa fa-check"></i><b>4.6</b> Preparation</a>
<ul>
<li class="chapter" data-level="4.6.1" data-path="data-visualization.html"><a href="data-visualization.html#create-a-new-rstudio-project"><i class="fa fa-check"></i><b>4.6.1</b> Create a New RStudio Project</a></li>
<li class="chapter" data-level="4.6.2" data-path="data-visualization.html"><a href="data-visualization.html#important-questions-when-making-graphs"><i class="fa fa-check"></i><b>4.6.2</b> Important Questions when Making Graphs</a></li>
<li class="chapter" data-level="4.6.3" data-path="data-visualization.html"><a href="data-visualization.html#read-data"><i class="fa fa-check"></i><b>4.6.3</b> Read Data</a></li>
<li class="chapter" data-level="4.6.4" data-path="data-visualization.html"><a href="data-visualization.html#load-the-library"><i class="fa fa-check"></i><b>4.6.4</b> Load the Library</a></li>
<li class="chapter" data-level="4.6.5" data-path="data-visualization.html"><a href="data-visualization.html#read-dataset"><i class="fa fa-check"></i><b>4.6.5</b> Read Dataset</a></li>
</ul></li>
<li class="chapter" data-level="4.7" data-path="data-visualization.html"><a href="data-visualization.html#basic-plots"><i class="fa fa-check"></i><b>4.7</b> Basic Plots</a></li>
<li class="chapter" data-level="4.8" data-path="data-visualization.html"><a href="data-visualization.html#adding-another-variable"><i class="fa fa-check"></i><b>4.8</b> Adding another variable</a></li>
<li class="chapter" data-level="4.9" data-path="data-visualization.html"><a href="data-visualization.html#making-subplots"><i class="fa fa-check"></i><b>4.9</b> Making Subplots</a></li>
<li class="chapter" data-level="4.10" data-path="data-visualization.html"><a href="data-visualization.html#overlaying-plots"><i class="fa fa-check"></i><b>4.10</b> Overlaying Plots</a></li>
<li class="chapter" data-level="4.11" data-path="data-visualization.html"><a href="data-visualization.html#combining-different-plots"><i class="fa fa-check"></i><b>4.11</b> Combining Different Plots</a></li>
<li class="chapter" data-level="4.12" data-path="data-visualization.html"><a href="data-visualization.html#statistical-transformation"><i class="fa fa-check"></i><b>4.12</b> Statistical Transformation</a></li>
<li class="chapter" data-level="4.13" data-path="data-visualization.html"><a href="data-visualization.html#customizing-title"><i class="fa fa-check"></i><b>4.13</b> Customizing Title</a></li>
<li class="chapter" data-level="4.14" data-path="data-visualization.html"><a href="data-visualization.html#adjusting-axes"><i class="fa fa-check"></i><b>4.14</b> Adjusting Axes</a></li>
<li class="chapter" data-level="4.15" data-path="data-visualization.html"><a href="data-visualization.html#choosing-themes"><i class="fa fa-check"></i><b>4.15</b> Choosing Themes</a></li>
<li class="chapter" data-level="4.16" data-path="data-visualization.html"><a href="data-visualization.html#saving-plots"><i class="fa fa-check"></i><b>4.16</b> Saving Plots</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="data-wrangling.html"><a href="data-wrangling.html"><i class="fa fa-check"></i><b>5</b> Data Wrangling</a>
<ul>
<li class="chapter" data-level="5.1" data-path="data-wrangling.html"><a href="data-wrangling.html#definition-of-data-wrangling"><i class="fa fa-check"></i><b>5.1</b> Definition of data wrangling</a></li>
<li class="chapter" data-level="5.2" data-path="data-wrangling.html"><a href="data-wrangling.html#data-wrangling-with-dplyr-package"><i class="fa fa-check"></i><b>5.2</b> Data wrangling with <strong>dplyr</strong> package</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="data-wrangling.html"><a href="data-wrangling.html#dplyr-package"><i class="fa fa-check"></i><b>5.2.1</b> <strong>dplyr</strong> package</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="data-wrangling.html"><a href="data-wrangling.html#common-procedures-for-doing-data-transformation"><i class="fa fa-check"></i><b>5.3</b> Common procedures for doing data transformation</a></li>
<li class="chapter" data-level="5.4" data-path="data-wrangling.html"><a href="data-wrangling.html#some-dplyr-functions"><i class="fa fa-check"></i><b>5.4</b> Some <strong>dplyr</strong> functions</a></li>
<li class="chapter" data-level="5.5" data-path="data-wrangling.html"><a href="data-wrangling.html#create-a-new-project-or-set-your-working-directory"><i class="fa fa-check"></i><b>5.5</b> Create a new project or set your working directory</a></li>
<li class="chapter" data-level="5.6" data-path="data-wrangling.html"><a href="data-wrangling.html#load-the-libraries"><i class="fa fa-check"></i><b>5.6</b> Load the libraries</a></li>
<li class="chapter" data-level="5.7" data-path="data-wrangling.html"><a href="data-wrangling.html#datasets"><i class="fa fa-check"></i><b>5.7</b> Datasets</a></li>
<li class="chapter" data-level="5.8" data-path="data-wrangling.html"><a href="data-wrangling.html#select-variables-generate-new-variable-and-rename-variable"><i class="fa fa-check"></i><b>5.8</b> Select variables, generate new variable and rename variable</a>
<ul>
<li class="chapter" data-level="5.8.1" data-path="data-wrangling.html"><a href="data-wrangling.html#select-variables-using-dplyrselect"><i class="fa fa-check"></i><b>5.8.1</b> Select variables using <code>dplyr::select()</code></a></li>
<li class="chapter" data-level="5.8.2" data-path="data-wrangling.html"><a href="data-wrangling.html#generate-new-variable-using-mutate"><i class="fa fa-check"></i><b>5.8.2</b> Generate new variable using <code>mutate()</code></a></li>
<li class="chapter" data-level="5.8.3" data-path="data-wrangling.html"><a href="data-wrangling.html#rename-variable-using-rename"><i class="fa fa-check"></i><b>5.8.3</b> Rename variable using <code>rename()</code></a></li>
</ul></li>
<li class="chapter" data-level="5.9" data-path="data-wrangling.html"><a href="data-wrangling.html#sorting-data-and-select-observation"><i class="fa fa-check"></i><b>5.9</b> Sorting data and select observation</a>
<ul>
<li class="chapter" data-level="5.9.1" data-path="data-wrangling.html"><a href="data-wrangling.html#sorting-data-using-arrange"><i class="fa fa-check"></i><b>5.9.1</b> Sorting data using <code>arrange()</code></a></li>
<li class="chapter" data-level="5.9.2" data-path="data-wrangling.html"><a href="data-wrangling.html#select-observation-using-filter"><i class="fa fa-check"></i><b>5.9.2</b> Select observation using <code>filter()</code></a></li>
</ul></li>
<li class="chapter" data-level="5.10" data-path="data-wrangling.html"><a href="data-wrangling.html#group-data-and-get-summary-statistics"><i class="fa fa-check"></i><b>5.10</b> Group data and get summary statistics</a>
<ul>
<li class="chapter" data-level="5.10.1" data-path="data-wrangling.html"><a href="data-wrangling.html#group-data-using-group_by"><i class="fa fa-check"></i><b>5.10.1</b> Group data using <code>group_by()</code></a></li>
<li class="chapter" data-level="5.10.2" data-path="data-wrangling.html"><a href="data-wrangling.html#summary-statistic-using-summarize"><i class="fa fa-check"></i><b>5.10.2</b> Summary statistic using <code>summarize()</code></a></li>
</ul></li>
<li class="chapter" data-level="5.11" data-path="data-wrangling.html"><a href="data-wrangling.html#more-complicated-dplyr-verbs"><i class="fa fa-check"></i><b>5.11</b> More complicated <strong>dplyr</strong> verbs</a></li>
<li class="chapter" data-level="5.12" data-path="data-wrangling.html"><a href="data-wrangling.html#data-transformation-for-categorical-variables"><i class="fa fa-check"></i><b>5.12</b> Data transformation for categorical variables</a>
<ul>
<li class="chapter" data-level="5.12.1" data-path="data-wrangling.html"><a href="data-wrangling.html#forcats-package"><i class="fa fa-check"></i><b>5.12.1</b> <strong>forcats</strong> package</a></li>
<li class="chapter" data-level="5.12.2" data-path="data-wrangling.html"><a href="data-wrangling.html#conversion-from-numeric-to-factor-variables"><i class="fa fa-check"></i><b>5.12.2</b> Conversion from numeric to factor variables</a></li>
<li class="chapter" data-level="5.12.3" data-path="data-wrangling.html"><a href="data-wrangling.html#recoding-variables"><i class="fa fa-check"></i><b>5.12.3</b> Recoding variables</a></li>
<li class="chapter" data-level="5.12.4" data-path="data-wrangling.html"><a href="data-wrangling.html#changing-the-level-of-categorical-variable"><i class="fa fa-check"></i><b>5.12.4</b> Changing the level of categorical variable</a></li>
</ul></li>
<li class="chapter" data-level="5.13" data-path="data-wrangling.html"><a href="data-wrangling.html#summary"><i class="fa fa-check"></i><b>5.13</b> Summary</a></li>
<li class="chapter" data-level="5.14" data-path="data-wrangling.html"><a href="data-wrangling.html#self-practice"><i class="fa fa-check"></i><b>5.14</b> Self-practice</a></li>
<li class="chapter" data-level="5.15" data-path="data-wrangling.html"><a href="data-wrangling.html#references"><i class="fa fa-check"></i><b>5.15</b> References</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="r-markdown.html"><a href="r-markdown.html"><i class="fa fa-check"></i><b>6</b> R Markdown</a>
<ul>
<li class="chapter" data-level="6.1" data-path="r-markdown.html"><a href="r-markdown.html#motivation"><i class="fa fa-check"></i><b>6.1</b> Motivation</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="r-markdown.html"><a href="r-markdown.html#what-is-r-markdown"><i class="fa fa-check"></i><b>6.1.1</b> What is R Markdown?</a></li>
<li class="chapter" data-level="6.1.2" data-path="r-markdown.html"><a href="r-markdown.html#why-should-we-bother-learning-r-markdown"><i class="fa fa-check"></i><b>6.1.2</b> Why should we bother learning R Markdown?</a></li>
<li class="chapter" data-level="6.1.3" data-path="r-markdown.html"><a href="r-markdown.html#sources-to-learn-r-markdown"><i class="fa fa-check"></i><b>6.1.3</b> Sources to learn R Markdown</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="r-markdown.html"><a href="r-markdown.html#r-markdown-basics"><i class="fa fa-check"></i><b>6.2</b> R Markdown Basics</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="r-markdown.html"><a href="r-markdown.html#install-rmarkdown-package"><i class="fa fa-check"></i><b>6.2.1</b> Install <code>rmarkdown</code> package</a></li>
<li class="chapter" data-level="6.2.2" data-path="r-markdown.html"><a href="r-markdown.html#install-latex-package-for-pdf"><i class="fa fa-check"></i><b>6.2.2</b> Install LaTeX package for PDF</a></li>
<li class="chapter" data-level="6.2.3" data-path="r-markdown.html"><a href="r-markdown.html#new-.rmd-file"><i class="fa fa-check"></i><b>6.2.3</b> New .Rmd file</a></li>
<li class="chapter" data-level="6.2.4" data-path="r-markdown.html"><a href="r-markdown.html#knit-it"><i class="fa fa-check"></i><b>6.2.4</b> Knit it!</a></li>
<li class="chapter" data-level="6.2.5" data-path="r-markdown.html"><a href="r-markdown.html#yaml-header"><i class="fa fa-check"></i><b>6.2.5</b> YAML header</a></li>
<li class="chapter" data-level="6.2.6" data-path="r-markdown.html"><a href="r-markdown.html#code-chunks"><i class="fa fa-check"></i><b>6.2.6</b> Code chunks</a></li>
<li class="chapter" data-level="6.2.7" data-path="r-markdown.html"><a href="r-markdown.html#header-levels"><i class="fa fa-check"></i><b>6.2.7</b> Header levels</a></li>
<li class="chapter" data-level="6.2.8" data-path="r-markdown.html"><a href="r-markdown.html#exercise-1"><i class="fa fa-check"></i><b>6.2.8</b> Exercise 1</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="r-markdown.html"><a href="r-markdown.html#table"><i class="fa fa-check"></i><b>6.3</b> Table</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="r-markdown.html"><a href="r-markdown.html#basic-table"><i class="fa fa-check"></i><b>6.3.1</b> Basic table</a></li>
<li class="chapter" data-level="6.3.2" data-path="r-markdown.html"><a href="r-markdown.html#table-from-data-frame"><i class="fa fa-check"></i><b>6.3.2</b> Table (from data frame)</a></li>
<li class="chapter" data-level="6.3.3" data-path="r-markdown.html"><a href="r-markdown.html#more-on-table"><i class="fa fa-check"></i><b>6.3.3</b> More on table</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="r-markdown.html"><a href="r-markdown.html#plot-figure-and-image"><i class="fa fa-check"></i><b>6.4</b> Plot, figure and image</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="r-markdown.html"><a href="r-markdown.html#plot-caption-fig.cap"><i class="fa fa-check"></i><b>6.4.1</b> Plot caption – <code>fig.cap</code></a></li>
<li class="chapter" data-level="6.4.2" data-path="r-markdown.html"><a href="r-markdown.html#plot-size-fig.heightin-inch"><i class="fa fa-check"></i><b>6.4.2</b> Plot size – <code>fig.height</code>(in inch)</a></li>
<li class="chapter" data-level="6.4.3" data-path="r-markdown.html"><a href="r-markdown.html#plot-size-fig.width-in-inch"><i class="fa fa-check"></i><b>6.4.3</b> Plot size – <code>fig.width</code> (in inch)</a></li>
<li class="chapter" data-level="6.4.4" data-path="r-markdown.html"><a href="r-markdown.html#plot-aspect-ratio-fig.asp"><i class="fa fa-check"></i><b>6.4.4</b> Plot aspect ratio – <code>fig.asp</code></a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="r-markdown.html"><a href="r-markdown.html#image"><i class="fa fa-check"></i><b>6.5</b> Image</a>
<ul>
<li class="chapter" data-level="6.5.1" data-path="r-markdown.html"><a href="r-markdown.html#exercise-2"><i class="fa fa-check"></i><b>6.5.1</b> Exercise 2</a></li>
</ul></li>
<li class="chapter" data-level="6.6" data-path="r-markdown.html"><a href="r-markdown.html#inline-output"><i class="fa fa-check"></i><b>6.6</b> Inline output</a></li>
<li class="chapter" data-level="6.7" data-path="r-markdown.html"><a href="r-markdown.html#equation"><i class="fa fa-check"></i><b>6.7</b> Equation</a>
<ul>
<li class="chapter" data-level="6.7.1" data-path="r-markdown.html"><a href="r-markdown.html#mathematical-equation"><i class="fa fa-check"></i><b>6.7.1</b> Mathematical equation</a></li>
<li class="chapter" data-level="6.7.2" data-path="r-markdown.html"><a href="r-markdown.html#inline-equation"><i class="fa fa-check"></i><b>6.7.2</b> Inline equation</a></li>
<li class="chapter" data-level="6.7.3" data-path="r-markdown.html"><a href="r-markdown.html#display-equation"><i class="fa fa-check"></i><b>6.7.3</b> Display equation</a></li>
<li class="chapter" data-level="6.7.4" data-path="r-markdown.html"><a href="r-markdown.html#exercise-3"><i class="fa fa-check"></i><b>6.7.4</b> Exercise 3</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="exploratory-data-analysis-eda.html"><a href="exploratory-data-analysis-eda.html"><i class="fa fa-check"></i><b>7</b> Exploratory data analysis (EDA)</a>
<ul>
<li class="chapter" data-level="7.1" data-path="exploratory-data-analysis-eda.html"><a href="exploratory-data-analysis-eda.html#motivation-1"><i class="fa fa-check"></i><b>7.1</b> Motivation</a></li>
<li class="chapter" data-level="7.2" data-path="exploratory-data-analysis-eda.html"><a href="exploratory-data-analysis-eda.html#questions-to-ask-before-making-graphs"><i class="fa fa-check"></i><b>7.2</b> Questions to ask before making graphs</a></li>
<li class="chapter" data-level="7.3" data-path="exploratory-data-analysis-eda.html"><a href="exploratory-data-analysis-eda.html#eda-using-ggplot2-package"><i class="fa fa-check"></i><b>7.3</b> EDA using ggplot2 package</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="exploratory-data-analysis-eda.html"><a href="exploratory-data-analysis-eda.html#usage-of-ggplot2"><i class="fa fa-check"></i><b>7.3.1</b> Usage of <strong>ggplot2</strong></a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="exploratory-data-analysis-eda.html"><a href="exploratory-data-analysis-eda.html#loading-the-library"><i class="fa fa-check"></i><b>7.4</b> Loading the library</a></li>
<li class="chapter" data-level="7.5" data-path="exploratory-data-analysis-eda.html"><a href="exploratory-data-analysis-eda.html#the-dataset"><i class="fa fa-check"></i><b>7.5</b> The dataset</a></li>
<li class="chapter" data-level="7.6" data-path="exploratory-data-analysis-eda.html"><a href="exploratory-data-analysis-eda.html#exploratory-data-analysis"><i class="fa fa-check"></i><b>7.6</b> Exploratory data analysis</a>
<ul>
<li class="chapter" data-level="7.6.1" data-path="exploratory-data-analysis-eda.html"><a href="exploratory-data-analysis-eda.html#statistics"><i class="fa fa-check"></i><b>7.6.1</b> Statistics</a></li>
<li class="chapter" data-level="7.6.2" data-path="exploratory-data-analysis-eda.html"><a href="exploratory-data-analysis-eda.html#plots"><i class="fa fa-check"></i><b>7.6.2</b> Plots</a></li>
</ul></li>
<li class="chapter" data-level="7.7" data-path="exploratory-data-analysis-eda.html"><a href="exploratory-data-analysis-eda.html#one-variable-distribution-of-a-categorical-variable"><i class="fa fa-check"></i><b>7.7</b> One variable: Distribution of a categorical variable</a>
<ul>
<li class="chapter" data-level="7.7.1" data-path="exploratory-data-analysis-eda.html"><a href="exploratory-data-analysis-eda.html#bar-chart"><i class="fa fa-check"></i><b>7.7.1</b> Bar chart</a></li>
</ul></li>
<li class="chapter" data-level="7.8" data-path="exploratory-data-analysis-eda.html"><a href="exploratory-data-analysis-eda.html#one-variable-distribution-of-a-numerical-variable"><i class="fa fa-check"></i><b>7.8</b> One variable: Distribution of a numerical variable</a>
<ul>
<li class="chapter" data-level="7.8.1" data-path="exploratory-data-analysis-eda.html"><a href="exploratory-data-analysis-eda.html#histogram"><i class="fa fa-check"></i><b>7.8.1</b> Histogram</a></li>
<li class="chapter" data-level="7.8.2" data-path="exploratory-data-analysis-eda.html"><a href="exploratory-data-analysis-eda.html#density-curve"><i class="fa fa-check"></i><b>7.8.2</b> Density curve</a></li>
<li class="chapter" data-level="7.8.3" data-path="exploratory-data-analysis-eda.html"><a href="exploratory-data-analysis-eda.html#histogram-and-density-curve-together"><i class="fa fa-check"></i><b>7.8.3</b> Histogram and density curve together</a></li>
</ul></li>
<li class="chapter" data-level="7.9" data-path="exploratory-data-analysis-eda.html"><a href="exploratory-data-analysis-eda.html#two-variables-plotting-a-numerical-and-a-categorical-variable"><i class="fa fa-check"></i><b>7.9</b> Two variables: Plotting a numerical and a categorical variable</a>
<ul>
<li class="chapter" data-level="7.9.1" data-path="exploratory-data-analysis-eda.html"><a href="exploratory-data-analysis-eda.html#overlaying-histogramss-and-boxplot"><i class="fa fa-check"></i><b>7.9.1</b> Overlaying histogramss and boxplot</a></li>
<li class="chapter" data-level="7.9.2" data-path="exploratory-data-analysis-eda.html"><a href="exploratory-data-analysis-eda.html#faceting-the-plots"><i class="fa fa-check"></i><b>7.9.2</b> Faceting the plots</a></li>
</ul></li>
<li class="chapter" data-level="7.10" data-path="exploratory-data-analysis-eda.html"><a href="exploratory-data-analysis-eda.html#line-plot"><i class="fa fa-check"></i><b>7.10</b> Line plot</a></li>
<li class="chapter" data-level="7.11" data-path="exploratory-data-analysis-eda.html"><a href="exploratory-data-analysis-eda.html#plotting-means-and-error-bars"><i class="fa fa-check"></i><b>7.11</b> Plotting means and error bars</a></li>
<li class="chapter" data-level="7.12" data-path="exploratory-data-analysis-eda.html"><a href="exploratory-data-analysis-eda.html#scatterplot-with-fit-line"><i class="fa fa-check"></i><b>7.12</b> Scatterplot with fit line</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="linear-regression.html"><a href="linear-regression.html"><i class="fa fa-check"></i><b>8</b> Linear Regression</a>
<ul>
<li class="chapter" data-level="8.1" data-path="linear-regression.html"><a href="linear-regression.html#simple-linear-regression-slr"><i class="fa fa-check"></i><b>8.1</b> Simple linear regression (SLR)</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="linear-regression.html"><a href="linear-regression.html#about-slr"><i class="fa fa-check"></i><b>8.1.1</b> About SLR</a></li>
<li class="chapter" data-level="8.1.2" data-path="linear-regression.html"><a href="linear-regression.html#analysis"><i class="fa fa-check"></i><b>8.1.2</b> Analysis</a></li>
<li class="chapter" data-level="8.1.3" data-path="linear-regression.html"><a href="linear-regression.html#data-exploration"><i class="fa fa-check"></i><b>8.1.3</b> Data exploration</a></li>
<li class="chapter" data-level="8.1.4" data-path="linear-regression.html"><a href="linear-regression.html#univariable"><i class="fa fa-check"></i><b>8.1.4</b> Univariable</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="linear-regression.html"><a href="linear-regression.html#multiple-linear-regression-mlr"><i class="fa fa-check"></i><b>8.2</b> Multiple linear regression (MLR)</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="linear-regression.html"><a href="linear-regression.html#about-mlr"><i class="fa fa-check"></i><b>8.2.1</b> About MLR</a></li>
<li class="chapter" data-level="8.2.2" data-path="linear-regression.html"><a href="linear-regression.html#analysis-1"><i class="fa fa-check"></i><b>8.2.2</b> Analysis</a></li>
<li class="chapter" data-level="8.2.3" data-path="linear-regression.html"><a href="linear-regression.html#multicollinearity-mc"><i class="fa fa-check"></i><b>8.2.3</b> Multicollinearity, MC</a></li>
<li class="chapter" data-level="8.2.4" data-path="linear-regression.html"><a href="linear-regression.html#interaction"><i class="fa fa-check"></i><b>8.2.4</b> Interaction, *</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="linear-regression.html"><a href="linear-regression.html#model-fit-assessment-residuals"><i class="fa fa-check"></i><b>8.3</b> Model fit assessment: Residuals</a>
<ul>
<li class="chapter" data-level="" data-path="linear-regression.html"><a href="linear-regression.html#histogram-1"><i class="fa fa-check"></i>Histogram</a></li>
<li class="chapter" data-level="" data-path="linear-regression.html"><a href="linear-regression.html#scatter-plots"><i class="fa fa-check"></i>Scatter plots</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="linear-regression.html"><a href="linear-regression.html#interpretation-1"><i class="fa fa-check"></i><b>8.4</b> Interpretation</a></li>
<li class="chapter" data-level="8.5" data-path="linear-regression.html"><a href="linear-regression.html#model-equation-1"><i class="fa fa-check"></i><b>8.5</b> Model equation</a></li>
<li class="chapter" data-level="8.6" data-path="linear-regression.html"><a href="linear-regression.html#prediction"><i class="fa fa-check"></i><b>8.6</b> Prediction</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="binary-logistic-regression.html"><a href="binary-logistic-regression.html"><i class="fa fa-check"></i><b>9</b> Binary Logistic Regression</a>
<ul>
<li class="chapter" data-level="9.1" data-path="binary-logistic-regression.html"><a href="binary-logistic-regression.html#introduction-1"><i class="fa fa-check"></i><b>9.1</b> Introduction</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="binary-logistic-regression.html"><a href="binary-logistic-regression.html#background"><i class="fa fa-check"></i><b>9.1.1</b> Background</a></li>
<li class="chapter" data-level="9.1.2" data-path="binary-logistic-regression.html"><a href="binary-logistic-regression.html#objectives-1"><i class="fa fa-check"></i><b>9.1.2</b> Objectives</a></li>
<li class="chapter" data-level="9.1.3" data-path="binary-logistic-regression.html"><a href="binary-logistic-regression.html#further-readings"><i class="fa fa-check"></i><b>9.1.3</b> Further readings</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="binary-logistic-regression.html"><a href="binary-logistic-regression.html#dataset"><i class="fa fa-check"></i><b>9.2</b> Dataset</a></li>
<li class="chapter" data-level="9.3" data-path="binary-logistic-regression.html"><a href="binary-logistic-regression.html#the-logit-and-logistic-models"><i class="fa fa-check"></i><b>9.3</b> The logit and logistic models</a></li>
<li class="chapter" data-level="9.4" data-path="binary-logistic-regression.html"><a href="binary-logistic-regression.html#prepare-environment-for-analysis"><i class="fa fa-check"></i><b>9.4</b> Prepare environment for analysis</a>
<ul>
<li class="chapter" data-level="9.4.1" data-path="binary-logistic-regression.html"><a href="binary-logistic-regression.html#creating-a-rstudio-project"><i class="fa fa-check"></i><b>9.4.1</b> Creating a RStudio project</a></li>
<li class="chapter" data-level="9.4.2" data-path="binary-logistic-regression.html"><a href="binary-logistic-regression.html#loading-libraries"><i class="fa fa-check"></i><b>9.4.2</b> Loading libraries</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="binary-logistic-regression.html"><a href="binary-logistic-regression.html#read-data-1"><i class="fa fa-check"></i><b>9.5</b> Read data</a></li>
<li class="chapter" data-level="9.6" data-path="binary-logistic-regression.html"><a href="binary-logistic-regression.html#explore-data"><i class="fa fa-check"></i><b>9.6</b> Explore data</a></li>
<li class="chapter" data-level="9.7" data-path="binary-logistic-regression.html"><a href="binary-logistic-regression.html#estimate-the-regression-parameters"><i class="fa fa-check"></i><b>9.7</b> Estimate the regression parameters</a></li>
<li class="chapter" data-level="9.8" data-path="binary-logistic-regression.html"><a href="binary-logistic-regression.html#simple-binary-logistic-regression"><i class="fa fa-check"></i><b>9.8</b> Simple binary logistic regression</a></li>
<li class="chapter" data-level="9.9" data-path="binary-logistic-regression.html"><a href="binary-logistic-regression.html#multiple-binary-logistic-regression"><i class="fa fa-check"></i><b>9.9</b> Multiple binary logistic regression</a></li>
<li class="chapter" data-level="9.10" data-path="binary-logistic-regression.html"><a href="binary-logistic-regression.html#convert-the-log-odds-to-odds-ratio"><i class="fa fa-check"></i><b>9.10</b> Convert the log odds to odds ratio</a></li>
<li class="chapter" data-level="9.11" data-path="binary-logistic-regression.html"><a href="binary-logistic-regression.html#making-inference"><i class="fa fa-check"></i><b>9.11</b> Making inference</a></li>
<li class="chapter" data-level="9.12" data-path="binary-logistic-regression.html"><a href="binary-logistic-regression.html#model-comparison"><i class="fa fa-check"></i><b>9.12</b> Model comparison</a></li>
<li class="chapter" data-level="9.13" data-path="binary-logistic-regression.html"><a href="binary-logistic-regression.html#adding-an-interaction-term"><i class="fa fa-check"></i><b>9.13</b> Adding an interaction term</a></li>
<li class="chapter" data-level="9.14" data-path="binary-logistic-regression.html"><a href="binary-logistic-regression.html#prediction-from-binary-logistic-regression"><i class="fa fa-check"></i><b>9.14</b> Prediction from binary logistic regression</a>
<ul>
<li class="chapter" data-level="9.14.1" data-path="binary-logistic-regression.html"><a href="binary-logistic-regression.html#predict-the-log-odds"><i class="fa fa-check"></i><b>9.14.1</b> Predict the log odds</a></li>
<li class="chapter" data-level="9.14.2" data-path="binary-logistic-regression.html"><a href="binary-logistic-regression.html#predict-the-probabilities"><i class="fa fa-check"></i><b>9.14.2</b> Predict the probabilities</a></li>
</ul></li>
<li class="chapter" data-level="9.15" data-path="binary-logistic-regression.html"><a href="binary-logistic-regression.html#model-fitness"><i class="fa fa-check"></i><b>9.15</b> Model fitness</a></li>
<li class="chapter" data-level="9.16" data-path="binary-logistic-regression.html"><a href="binary-logistic-regression.html#presentation"><i class="fa fa-check"></i><b>9.16</b> Presentation</a></li>
<li class="chapter" data-level="9.17" data-path="binary-logistic-regression.html"><a href="binary-logistic-regression.html#references-1"><i class="fa fa-check"></i><b>9.17</b> References</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="poisson-regression.html"><a href="poisson-regression.html"><i class="fa fa-check"></i><b>10</b> Poisson Regression</a>
<ul>
<li class="chapter" data-level="10.1" data-path="poisson-regression.html"><a href="poisson-regression.html#introduction-2"><i class="fa fa-check"></i><b>10.1</b> Introduction</a></li>
<li class="chapter" data-level="10.2" data-path="poisson-regression.html"><a href="poisson-regression.html#preliminaries"><i class="fa fa-check"></i><b>10.2</b> Preliminaries</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="poisson-regression.html"><a href="poisson-regression.html#load-libraries"><i class="fa fa-check"></i><b>10.2.1</b> Load libraries</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="poisson-regression.html"><a href="poisson-regression.html#simple-poisson-regression-models"><i class="fa fa-check"></i><b>10.3</b> Simple Poisson regression models</a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="poisson-regression.html"><a href="poisson-regression.html#count-data"><i class="fa fa-check"></i><b>10.3.1</b> Count data</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="poisson-regression.html"><a href="poisson-regression.html#rate-data"><i class="fa fa-check"></i><b>10.4</b> Rate data</a></li>
<li class="chapter" data-level="10.5" data-path="poisson-regression.html"><a href="poisson-regression.html#multiple-poisson-regression-model"><i class="fa fa-check"></i><b>10.5</b> Multiple Poisson regression model</a>
<ul>
<li class="chapter" data-level="10.5.1" data-path="poisson-regression.html"><a href="poisson-regression.html#univariable-1"><i class="fa fa-check"></i><b>10.5.1</b> Univariable</a></li>
<li class="chapter" data-level="10.5.2" data-path="poisson-regression.html"><a href="poisson-regression.html#multivariable-1"><i class="fa fa-check"></i><b>10.5.2</b> Multivariable</a></li>
<li class="chapter" data-level="10.5.3" data-path="poisson-regression.html"><a href="poisson-regression.html#interaction-1"><i class="fa fa-check"></i><b>10.5.3</b> Interaction</a></li>
<li class="chapter" data-level="10.5.4" data-path="poisson-regression.html"><a href="poisson-regression.html#final-model"><i class="fa fa-check"></i><b>10.5.4</b> Final model</a></li>
</ul></li>
<li class="chapter" data-level="10.6" data-path="poisson-regression.html"><a href="poisson-regression.html#references-2"><i class="fa fa-check"></i><b>10.6</b> References</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="survival-analysis.html"><a href="survival-analysis.html"><i class="fa fa-check"></i><b>11</b> Survival Analysis</a>
<ul>
<li class="chapter" data-level="11.1" data-path="survival-analysis.html"><a href="survival-analysis.html#introduction-3"><i class="fa fa-check"></i><b>11.1</b> Introduction</a>
<ul>
<li class="chapter" data-level="11.1.1" data-path="survival-analysis.html"><a href="survival-analysis.html#background-1"><i class="fa fa-check"></i><b>11.1.1</b> Background</a></li>
<li class="chapter" data-level="11.1.2" data-path="survival-analysis.html"><a href="survival-analysis.html#types-of-survival-analysis"><i class="fa fa-check"></i><b>11.1.2</b> Types of survival analysis</a></li>
<li class="chapter" data-level="11.1.3" data-path="survival-analysis.html"><a href="survival-analysis.html#objectives-2"><i class="fa fa-check"></i><b>11.1.3</b> Objectives</a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="survival-analysis.html"><a href="survival-analysis.html#prepare-environment-for-analysis-1"><i class="fa fa-check"></i><b>11.2</b> Prepare environment for analysis</a>
<ul>
<li class="chapter" data-level="11.2.1" data-path="survival-analysis.html"><a href="survival-analysis.html#rstudio-project-1"><i class="fa fa-check"></i><b>11.2.1</b> RStudio project</a></li>
<li class="chapter" data-level="11.2.2" data-path="survival-analysis.html"><a href="survival-analysis.html#packages-1"><i class="fa fa-check"></i><b>11.2.2</b> Packages</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="survival-analysis.html"><a href="survival-analysis.html#data"><i class="fa fa-check"></i><b>11.3</b> Data</a></li>
<li class="chapter" data-level="11.4" data-path="survival-analysis.html"><a href="survival-analysis.html#exploratory-data"><i class="fa fa-check"></i><b>11.4</b> Exploratory data</a></li>
<li class="chapter" data-level="11.5" data-path="survival-analysis.html"><a href="survival-analysis.html#kaplan-meier-survival-estimates"><i class="fa fa-check"></i><b>11.5</b> Kaplan-Meier survival estimates</a></li>
<li class="chapter" data-level="11.6" data-path="survival-analysis.html"><a href="survival-analysis.html#plot-the-survival-probability"><i class="fa fa-check"></i><b>11.6</b> Plot the survival probability</a></li>
<li class="chapter" data-level="11.7" data-path="survival-analysis.html"><a href="survival-analysis.html#comparing-kaplan-meier-estimates-across-groups"><i class="fa fa-check"></i><b>11.7</b> Comparing Kaplan-Meier estimates across groups</a>
<ul>
<li class="chapter" data-level="11.7.1" data-path="survival-analysis.html"><a href="survival-analysis.html#log-rank-test"><i class="fa fa-check"></i><b>11.7.1</b> Log-rank test</a></li>
<li class="chapter" data-level="11.7.2" data-path="survival-analysis.html"><a href="survival-analysis.html#peto-peto-test"><i class="fa fa-check"></i><b>11.7.2</b> peto-peto test</a></li>
</ul></li>
<li class="chapter" data-level="11.8" data-path="survival-analysis.html"><a href="survival-analysis.html#semi-parametric-models-in-survival-analysis"><i class="fa fa-check"></i><b>11.8</b> Semi-parametric models in survival analysis</a>
<ul>
<li class="chapter" data-level="11.8.1" data-path="survival-analysis.html"><a href="survival-analysis.html#cox-proportional-hazard-regression"><i class="fa fa-check"></i><b>11.8.1</b> Cox proportional hazard regression</a></li>
<li class="chapter" data-level="11.8.2" data-path="survival-analysis.html"><a href="survival-analysis.html#advantages-of-the-cox-proportional-hazard-regression"><i class="fa fa-check"></i><b>11.8.2</b> Advantages of the Cox proportional hazard regression</a></li>
</ul></li>
<li class="chapter" data-level="11.9" data-path="survival-analysis.html"><a href="survival-analysis.html#estimation-from-cox-proportional-hazards-regression"><i class="fa fa-check"></i><b>11.9</b> Estimation from Cox proportional hazards regression</a>
<ul>
<li class="chapter" data-level="11.9.1" data-path="survival-analysis.html"><a href="survival-analysis.html#simple-cox-ph-regression"><i class="fa fa-check"></i><b>11.9.1</b> Simple Cox PH regression</a></li>
<li class="chapter" data-level="11.9.2" data-path="survival-analysis.html"><a href="survival-analysis.html#multiple-cox-ph-regression"><i class="fa fa-check"></i><b>11.9.2</b> Multiple Cox PH regression</a></li>
</ul></li>
<li class="chapter" data-level="11.10" data-path="survival-analysis.html"><a href="survival-analysis.html#inference"><i class="fa fa-check"></i><b>11.10</b> Inference</a></li>
<li class="chapter" data-level="11.11" data-path="survival-analysis.html"><a href="survival-analysis.html#adding-interaction-in-the-model"><i class="fa fa-check"></i><b>11.11</b> Adding interaction in the model</a></li>
<li class="chapter" data-level="11.12" data-path="survival-analysis.html"><a href="survival-analysis.html#the-proportional-hazard-assumption"><i class="fa fa-check"></i><b>11.12</b> The proportional hazard assumption</a>
<ul>
<li class="chapter" data-level="11.12.1" data-path="survival-analysis.html"><a href="survival-analysis.html#risk-constant-over-time"><i class="fa fa-check"></i><b>11.12.1</b> Risk constant over time</a></li>
<li class="chapter" data-level="11.12.2" data-path="survival-analysis.html"><a href="survival-analysis.html#test-for-ph-assumption"><i class="fa fa-check"></i><b>11.12.2</b> Test for PH assumption</a></li>
<li class="chapter" data-level="11.12.3" data-path="survival-analysis.html"><a href="survival-analysis.html#plots-to-assess-ph-assumption"><i class="fa fa-check"></i><b>11.12.3</b> Plots to assess PH assumption</a></li>
</ul></li>
<li class="chapter" data-level="11.13" data-path="survival-analysis.html"><a href="survival-analysis.html#model-checking"><i class="fa fa-check"></i><b>11.13</b> Model checking</a>
<ul>
<li class="chapter" data-level="11.13.1" data-path="survival-analysis.html"><a href="survival-analysis.html#prediction-from-cox-ph-model"><i class="fa fa-check"></i><b>11.13.1</b> Prediction from Cox PH model</a></li>
<li class="chapter" data-level="11.13.2" data-path="survival-analysis.html"><a href="survival-analysis.html#residuas-from-cox-ph-model"><i class="fa fa-check"></i><b>11.13.2</b> Residuas from Cox PH model</a></li>
<li class="chapter" data-level="11.13.3" data-path="survival-analysis.html"><a href="survival-analysis.html#influential-observations"><i class="fa fa-check"></i><b>11.13.3</b> Influential observations</a></li>
</ul></li>
<li class="chapter" data-level="11.14" data-path="survival-analysis.html"><a href="survival-analysis.html#plot-the-adjusted-survival"><i class="fa fa-check"></i><b>11.14</b> Plot the adjusted survival</a></li>
<li class="chapter" data-level="11.15" data-path="survival-analysis.html"><a href="survival-analysis.html#presentation-and-interpretation"><i class="fa fa-check"></i><b>11.15</b> Presentation and interpretation</a></li>
<li class="chapter" data-level="11.16" data-path="survival-analysis.html"><a href="survival-analysis.html#references-3"><i class="fa fa-check"></i><b>11.16</b> References</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="missing-data.html"><a href="missing-data.html"><i class="fa fa-check"></i><b>12</b> Missing data</a>
<ul>
<li class="chapter" data-level="12.1" data-path="missing-data.html"><a href="missing-data.html#introduction-4"><i class="fa fa-check"></i><b>12.1</b> Introduction</a>
<ul>
<li class="chapter" data-level="12.1.1" data-path="missing-data.html"><a href="missing-data.html#background-2"><i class="fa fa-check"></i><b>12.1.1</b> Background</a></li>
<li class="chapter" data-level="12.1.2" data-path="missing-data.html"><a href="missing-data.html#objectives-3"><i class="fa fa-check"></i><b>12.1.2</b> Objectives</a></li>
</ul></li>
<li class="chapter" data-level="12.2" data-path="missing-data.html"><a href="missing-data.html#preliminaries-1"><i class="fa fa-check"></i><b>12.2</b> Preliminaries</a>
<ul>
<li class="chapter" data-level="12.2.1" data-path="missing-data.html"><a href="missing-data.html#packages-2"><i class="fa fa-check"></i><b>12.2.1</b> Packages</a></li>
<li class="chapter" data-level="12.2.2" data-path="missing-data.html"><a href="missing-data.html#dataset-1"><i class="fa fa-check"></i><b>12.2.2</b> Dataset</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="missing-data.html"><a href="missing-data.html#exploring-missing-data"><i class="fa fa-check"></i><b>12.3</b> Exploring missing data</a></li>
<li class="chapter" data-level="12.4" data-path="missing-data.html"><a href="missing-data.html#handling-missing-data"><i class="fa fa-check"></i><b>12.4</b> Handling missing data</a>
<ul>
<li class="chapter" data-level="12.4.1" data-path="missing-data.html"><a href="missing-data.html#listwise-deletion"><i class="fa fa-check"></i><b>12.4.1</b> Listwise deletion</a></li>
<li class="chapter" data-level="12.4.2" data-path="missing-data.html"><a href="missing-data.html#simple-imputation"><i class="fa fa-check"></i><b>12.4.2</b> Simple imputation</a></li>
<li class="chapter" data-level="12.4.3" data-path="missing-data.html"><a href="missing-data.html#single-imputation"><i class="fa fa-check"></i><b>12.4.3</b> Single imputation</a></li>
<li class="chapter" data-level="12.4.4" data-path="missing-data.html"><a href="missing-data.html#multiple-imputation"><i class="fa fa-check"></i><b>12.4.4</b> Multiple imputation</a></li>
</ul></li>
<li class="chapter" data-level="12.5" data-path="missing-data.html"><a href="missing-data.html#presentation-1"><i class="fa fa-check"></i><b>12.5</b> Presentation</a></li>
<li class="chapter" data-level="12.6" data-path="missing-data.html"><a href="missing-data.html#references-4"><i class="fa fa-check"></i><b>12.6</b> References</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references-5.html"><a href="references-5.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://bookdown.org" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Data Analysis in Medicine and Health using R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="binary-logistic-regression" class="section level1" number="9">
<h1><span class="header-section-number">Chapter 9</span> Binary Logistic Regression</h1>
<div id="introduction-1" class="section level2" number="9.1">
<h2><span class="header-section-number">9.1</span> Introduction</h2>
<div id="background" class="section level3" number="9.1.1">
<h3><span class="header-section-number">9.1.1</span> Background</h3>
<p>The logistic model (or logit model) is used to model the probability of a certain class or event existing such as pass or fail, win or lose, alive or dead or healthy or sick. More specifically, binary logistic regression is used to model the relationship between a covariate or a set of covariates and an outcome variables which is a binary variable.</p>
<p>A binary variable is a categorical outcome has two categories or levels. In medical and health research, binary outcome variable is very common. Some example where the outcome is binary include:</p>
<ul>
<li>survival status when the status of cancer patients at the end of treatment are coded as either alive or dead</li>
<li>relapse status when the status of a patient is coded as either relapse or not relapse</li>
<li>satisfaction level when patients who come to clinics are asked if they are satisfied or not satisfied with the service</li>
<li>glucose control when patients were categorized as either good control or poor control based on Hba1c</li>
</ul>
<p>In a binary logistic regression model, the dependent variable has two levels (categorical). When the outcome variable has more than two levels or categories, the analysis are modeled by multinomial logistic regression and, if the multiple categories are ordered, by ordinal logistic regression (for example the proportional odds ordinal logistic model).</p>
</div>
<div id="objectives-1" class="section level3" number="9.1.2">
<h3><span class="header-section-number">9.1.2</span> Objectives</h3>
<p>At the end of the chapter, the readers will be</p>
<ul>
<li>to understand the concept of simple and multiple binary logistic regression</li>
<li>to perform simple binary logistic regression</li>
<li>to perform multiple binary logistic regression</li>
<li>to perform model assessment of binary logistic regression</li>
<li>to present and interpret results from binary logsitic regression</li>
</ul>
</div>
<div id="further-readings" class="section level3" number="9.1.3">
<h3><span class="header-section-number">9.1.3</span> Further readings</h3>
<p>There are a number of good references to help readers understand binary logistic regression better. The references that we list below also contains workflow that wil be useful for readers when modelling logistic regression.</p>
<p>We highly recommend readers to read</p>
<ul>
<li>the Applied Logistic Regression book <span class="citation">(<a href="#ref-hosmer2013applied" role="doc-biblioref"><strong>hosmer2013applied?</strong></a>)</span></li>
<li>the Logistic Regression: Self Learning Text <span class="citation">(<a href="#ref-kleinbaum2010logistic" role="doc-biblioref"><strong>kleinbaum2010logistic?</strong></a>)</span></li>
<li>the workflow from A Handbook of Statistical Analyses Using R <span class="citation">(<a href="#ref-R-HSAUR" role="doc-biblioref"><strong>R-HSAUR?</strong></a>)</span></li>
</ul>
</div>
</div>
<div id="dataset" class="section level2" number="9.2">
<h2><span class="header-section-number">9.2</span> Dataset</h2>
<p>We will use a dataset named <code>stroke.dta</code> which in STATA format. These data come from a study of hospitalized stroke patients. They original dataset contain 12 variables but our main variables of interest are:</p>
<ul>
<li>status : Status of patient during hospitalization (alive or dead)</li>
<li>gcs : Glasgow Coma Scale on admission (range from 3 to 15)</li>
<li>stroke_type : IS (Ischaemic Stroke) or HS (Haemorrhagic Stroke)</li>
<li>sex : female or male</li>
<li>dm : History of Diabetes (yes or no)</li>
<li>sbp : Systolic Blood Pressure (mmHg)</li>
<li>age : age of patient on admission</li>
</ul>
<p>The outcome variable is variable status. It is labelled as either dead or alive which is the outcome of each patient during hospitalization.</p>
</div>
<div id="the-logit-and-logistic-models" class="section level2" number="9.3">
<h2><span class="header-section-number">9.3</span> The logit and logistic models</h2>
<p>The simple binary logit and logistic models refer to a a model with only one covariate (also known as independent variable). For example, if the covariate is gcs (Glasgow Coma Scale), the simple logit model is written as:</p>
<p><span class="math display">\[\hat{g}(x)= ln\left[ \frac{\hat\pi(x)}{1 - {\hat\pi(x)}} \right]\]</span></p>
<p>where <span class="math inline">\(\hat{g}(x)\)</span> is the log odds for death for a given value of gcs. And the odds for death for a given value of GCS is written as <span class="math inline">\(= \hat\beta_0 + \hat\beta_1(gcs)\)</span></p>
<p>And the simple logistic model is also written as:</p>
<p><span class="math display">\[\hat{\pi}(x) = \frac{exp^{\hat{\beta}_{0} + \hat{\beta}_{1}{gcs}}}{1 + exp^{\hat{\beta}_{0} + \hat{\beta}_{1}{gcs}}}\]</span>
The <span class="math inline">\(\pi(x) = E(Y|x)\)</span> represents the conditional mean of <span class="math inline">\(Y\)</span> given <span class="math inline">\(x\)</span> when the logistic distribution is used. This is also simply known as the predicted probability of death for given value of gcs.</p>
<p>If we have decided (based on our clinical expertise and literature review) that a model that could explain death consists of gcs, stroke type, sex, dm, age and sbp, then the logit model can be expanded to:</p>
<p><span class="math display">\[\hat{g}(x)  = \hat\beta_0 + \hat\beta_1(gcs) + \hat\beta_2(stroke type) + \hat\beta_3(sex)+ \hat\beta_4(dm) + \hat\beta_5(sbp) +  \hat\beta_6(age)\]</span>
This is the odds for death given certain value of gcs, sbp and age and certain categories of stroke stype, sex and diabetes. While the probability of deaths is</p>
<p><span class="math display">\[\hat{\pi}(x) = \frac{exp^{\hat\beta_0 + \hat\beta_1(gcs) + \hat\beta_2(stroke type) + \hat\beta_3(sex)+ \hat\beta_4(dm) + \hat\beta_5(sbp) + \hat\beta_6(age)})}{1 + exp^{\hat\beta_0 + \hat\beta_1(gcs) + \hat\beta_2(stroke type) + \hat\beta_3(sex)+ \hat\beta_4(dm) + \hat\beta_5(sbp) + \hat\beta_6(age)}}\]</span></p>
<p>In many datasets, some of the independent variables are discrete, nominal scale variables such as race, sex, treatment group, and so forth. And because of that it is inappropriate to include them in the model as if they were interval scale variables. Though in many software, they are represented by numbers, but these numbers are used merely identifiers.</p>
<p>In this situation, we will use a method called design variables (or dummy variables). Suppose, for example, assuming that one of the independent variables is obesity type, which is now coded as “Class 1,” “Class 2” and “Class 3.” In this case, there are 3 levels or categories, hence two design variables (<span class="math inline">\(D - 1\)</span>) are necessary, let’s say D1 and D2. One possible coding strategy is that when the patient is in “Class 1” then the two design variables, for D1 and D2 would both be set equal to zero. In this example, “Class 1” is the reference category. When the patient is in “Class 2,” then D1 is set as 1 and D2 as 0; when the patient is in “Class 3,” the we will set D1 as 0 and D2 and 1. All these coding assignment can be done automatically in the software. But to interpret, we must know which category is the reference.</p>
</div>
<div id="prepare-environment-for-analysis" class="section level2" number="9.4">
<h2><span class="header-section-number">9.4</span> Prepare environment for analysis</h2>
<div id="creating-a-rstudio-project" class="section level3" number="9.4.1">
<h3><span class="header-section-number">9.4.1</span> Creating a RStudio project</h3>
<p>Start a new analysis task by creating a new RStudio project. To do this,</p>
<ol style="list-style-type: decimal">
<li>Go to File</li>
<li>Click New Project</li>
<li>Choose New Directory or Existing Directory.</li>
</ol>
<p>This directory points to the folder that usually contains the dataset to be analyzed. This is called as the working directory. Make sure there is a folder named as <code>data</code> in the folder. If there is not, create one. Make sure the dataset <code>stroke.dta</code> is inside the <code>data</code> folder in the working directory.</p>
</div>
<div id="loading-libraries" class="section level3" number="9.4.2">
<h3><span class="header-section-number">9.4.2</span> Loading libraries</h3>
<p>Next, we will load the necessary packages. We will use 5 packages</p>
<ol style="list-style-type: decimal">
<li>the built in <strong>stat</strong> package - to run Generalized Linear Model. This is already loaded by default.</li>
<li><strong>haven</strong> - to read SPSS, STATA and SAS dataset</li>
<li><strong>tidyverse</strong> - to perform data transformation</li>
<li><strong>gtsummary</strong> - to provide nice results in a table<br />
</li>
<li><strong>broom</strong> - to tidy up the results</li>
<li><strong>LogisticDx</strong> - to do model assessment</li>
<li><strong>here</strong> - to ensure proper directory</li>
</ol>
<p>To load these packages, we will use the function <code>library()</code>:</p>
<div class="sourceCode" id="cb331"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb331-1"><a href="binary-logistic-regression.html#cb331-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(haven)</span>
<span id="cb331-2"><a href="binary-logistic-regression.html#cb331-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code></pre></div>
<pre><code>## -- Attaching packages --------------------------------------- tidyverse 1.3.1 --</code></pre>
<pre><code>## v ggplot2 3.3.5     v purrr   0.3.4
## v tibble  3.1.6     v dplyr   1.0.7
## v tidyr   1.1.4     v stringr 1.4.0
## v readr   2.1.1     v forcats 0.5.1</code></pre>
<pre><code>## Warning: package &#39;tibble&#39; was built under R version 4.1.2</code></pre>
<pre><code>## -- Conflicts ------------------------------------------ tidyverse_conflicts() --
## x dplyr::filter() masks stats::filter()
## x dplyr::lag()    masks stats::lag()</code></pre>
<div class="sourceCode" id="cb336"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb336-1"><a href="binary-logistic-regression.html#cb336-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gtsummary)</span></code></pre></div>
<pre><code>## #Uighur</code></pre>
<div class="sourceCode" id="cb338"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb338-1"><a href="binary-logistic-regression.html#cb338-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb338-2"><a href="binary-logistic-regression.html#cb338-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(LogisticDx)</span></code></pre></div>
<pre><code>## Warning: package &#39;LogisticDx&#39; was built under R version 4.1.2</code></pre>
<div class="sourceCode" id="cb340"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb340-1"><a href="binary-logistic-regression.html#cb340-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(here)</span></code></pre></div>
<pre><code>## here() starts at C:/Tengku/Sync_PC_Laptop/tulis-buku/multivariable-analysis/fork-profKIM/multivar_data_analysis</code></pre>
</div>
</div>
<div id="read-data-1" class="section level2" number="9.5">
<h2><span class="header-section-number">9.5</span> Read data</h2>
<p>WE will read data in the working directory into our R environment. Remember the dataset is in the STATA format.</p>
<div class="sourceCode" id="cb342"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb342-1"><a href="binary-logistic-regression.html#cb342-1" aria-hidden="true" tabindex="-1"></a>fatal <span class="ot">&lt;-</span> <span class="fu">read_dta</span>(<span class="fu">here</span>(<span class="st">&#39;data&#39;</span>,<span class="st">&#39;stroke.dta&#39;</span>))</span></code></pre></div>
<p>Take a peek at data. Check</p>
<ul>
<li>variable names</li>
<li>variable types</li>
</ul>
<div class="sourceCode" id="cb343"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb343-1"><a href="binary-logistic-regression.html#cb343-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(fatal)</span></code></pre></div>
<pre><code>## Rows: 226
## Columns: 7
## $ sex         &lt;dbl+lbl&gt; 1, 1, 1, 2, 1, 2, 2, 1, 2, 2, 1, 2, 2, 2, 2, 1, 2, 1, ~
## $ status      &lt;dbl+lbl&gt; 1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, ~
## $ gcs         &lt;dbl&gt; 13, 15, 15, 15, 15, 15, 13, 15, 15, 10, 15, 15, 15, 15, 15~
## $ sbp         &lt;dbl&gt; 143, 150, 152, 215, 162, 169, 178, 180, 186, 185, 122, 211~
## $ dm          &lt;dbl+lbl&gt; 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, ~
## $ age         &lt;dbl&gt; 50, 58, 64, 50, 65, 78, 66, 72, 61, 64, 63, 59, 64, 62, 40~
## $ stroke_type &lt;dbl+lbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ~</code></pre>
</div>
<div id="explore-data" class="section level2" number="9.6">
<h2><span class="header-section-number">9.6</span> Explore data</h2>
<p>Variables sex, status, dm and stroke type are labelled variable. This means eventhough they are coded as numbers but the numbers represent the groups or categories or levels of the variables. Basically, they are categorical variables.</p>
<p>We will transform all of them to factor variables. We can quickly do this using the function <code>across()</code>. Below, we will transform all labelled variables to factor variables:</p>
<div class="sourceCode" id="cb345"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb345-1"><a href="binary-logistic-regression.html#cb345-1" aria-hidden="true" tabindex="-1"></a>fatal <span class="ot">&lt;-</span> </span>
<span id="cb345-2"><a href="binary-logistic-regression.html#cb345-2" aria-hidden="true" tabindex="-1"></a>  fatal <span class="sc">%&gt;%</span></span>
<span id="cb345-3"><a href="binary-logistic-regression.html#cb345-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">where</span>(is.labelled), as_factor))</span></code></pre></div>
<p>Now, we can look at the summary statistics</p>
<div class="sourceCode" id="cb346"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb346-1"><a href="binary-logistic-regression.html#cb346-1" aria-hidden="true" tabindex="-1"></a>fatal <span class="sc">%&gt;%</span></span>
<span id="cb346-2"><a href="binary-logistic-regression.html#cb346-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tbl_summary</span>() <span class="sc">%&gt;%</span></span>
<span id="cb346-3"><a href="binary-logistic-regression.html#cb346-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_hux_table</span>()</span></code></pre></div>
<table class="huxtable" style="border-collapse: collapse; border: 0px; margin-bottom: 2em; margin-top: 2em; ; margin-left: auto; margin-right: auto;  " id="tab:unnamed-chunk-5">
<caption style="caption-side: top; text-align: center;"><span id="tab:unnamed-chunk-5">TABLE 9.1: </span> </caption><col><col><tr>
<td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;"><p><strong>Characteristic</strong></p>
</td><td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;"><p><strong>N = 226</strong></p>
</td></tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">sex</td><td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;"></td></tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 15pt; font-weight: normal;">male</td><td style="vertical-align: top; text-align: center; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">97 (43%)</td></tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 15pt; font-weight: normal;">female</td><td style="vertical-align: top; text-align: center; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">129 (57%)</td></tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">alive or dead</td><td style="vertical-align: top; text-align: center; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;"></td></tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 15pt; font-weight: normal;">alive</td><td style="vertical-align: top; text-align: center; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">171 (76%)</td></tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 15pt; font-weight: normal;">dead</td><td style="vertical-align: top; text-align: center; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">55 (24%)</td></tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">earliest Glasgow Coma Scale</td><td style="vertical-align: top; text-align: center; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">15.0 (10.0, 15.0)</td></tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">earliest systolic BP (mmHg)</td><td style="vertical-align: top; text-align: center; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">161 (143, 187)</td></tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">diabetes (yes or no)</td><td style="vertical-align: top; text-align: center; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">138 (61%)</td></tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">age in years</td><td style="vertical-align: top; text-align: center; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">61 (52, 69)</td></tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">Ischaemic Stroke or Haemorrhagic</td><td style="vertical-align: top; text-align: center; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;"></td></tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 15pt; font-weight: normal;">Ischaemic Stroke</td><td style="vertical-align: top; text-align: center; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">149 (66%)</td></tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;    padding: 6pt 6pt 6pt 15pt; font-weight: normal;">Haemorrhagic</td><td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">77 (34%)</td></tr>
<tr>
<td colspan="2" style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">n (%); Median (IQR)</td></tr>
</table>

<p>or to get summary statistics for each status category:</p>
<div class="sourceCode" id="cb347"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb347-1"><a href="binary-logistic-regression.html#cb347-1" aria-hidden="true" tabindex="-1"></a>fatal <span class="sc">%&gt;%</span></span>
<span id="cb347-2"><a href="binary-logistic-regression.html#cb347-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tbl_summary</span>(<span class="at">by =</span> status) <span class="sc">%&gt;%</span></span>
<span id="cb347-3"><a href="binary-logistic-regression.html#cb347-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_hux_table</span>()</span></code></pre></div>
<table class="huxtable" style="border-collapse: collapse; border: 0px; margin-bottom: 2em; margin-top: 2em; ; margin-left: auto; margin-right: auto;  " id="tab:unnamed-chunk-6">
<caption style="caption-side: top; text-align: center;"><span id="tab:unnamed-chunk-6">TABLE 9.2: </span> </caption><col><col><col><tr>
<td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;"><p><strong>Characteristic</strong></p>
</td><td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;"><p><strong>alive</strong>, N = 171</p>
</td><td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;"><p><strong>dead</strong>, N = 55</p>
</td></tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">sex</td><td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;"></td><td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;"></td></tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 15pt; font-weight: normal;">male</td><td style="vertical-align: top; text-align: center; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">81 (47%)</td><td style="vertical-align: top; text-align: center; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">16 (29%)</td></tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 15pt; font-weight: normal;">female</td><td style="vertical-align: top; text-align: center; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">90 (53%)</td><td style="vertical-align: top; text-align: center; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">39 (71%)</td></tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">earliest Glasgow Coma Scale</td><td style="vertical-align: top; text-align: center; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">15.0 (14.0, 15.0)</td><td style="vertical-align: top; text-align: center; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">8.0 (5.0, 11.0)</td></tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">earliest systolic BP (mmHg)</td><td style="vertical-align: top; text-align: center; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">160 (143, 186)</td><td style="vertical-align: top; text-align: center; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">162 (140, 199)</td></tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">diabetes (yes or no)</td><td style="vertical-align: top; text-align: center; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">100 (58%)</td><td style="vertical-align: top; text-align: center; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">38 (69%)</td></tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">age in years</td><td style="vertical-align: top; text-align: center; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">61 (53, 68)</td><td style="vertical-align: top; text-align: center; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">62 (50, 73)</td></tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">Ischaemic Stroke or Haemorrhagic</td><td style="vertical-align: top; text-align: center; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;"></td><td style="vertical-align: top; text-align: center; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;"></td></tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 15pt; font-weight: normal;">Ischaemic Stroke</td><td style="vertical-align: top; text-align: center; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">132 (77%)</td><td style="vertical-align: top; text-align: center; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">17 (31%)</td></tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;    padding: 6pt 6pt 6pt 15pt; font-weight: normal;">Haemorrhagic</td><td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">39 (23%)</td><td style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">38 (69%)</td></tr>
<tr>
<td colspan="3" style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">n (%); Median (IQR)</td></tr>
</table>

</div>
<div id="estimate-the-regression-parameters" class="section level2" number="9.7">
<h2><span class="header-section-number">9.7</span> Estimate the regression parameters</h2>
<p>We now can perform binary logistic regression to estimate the regression parameters <span class="math inline">\(\hat\beta_s\)</span> or the log odds. Usually, we can do this in two steps:</p>
<ol style="list-style-type: decimal">
<li>The simple binary logistic regression or the univariable logistic regression. In this analysis, there is only one independent variable or covariate in the model. This is also known as the crude or unadjusted analysis.</li>
<li>The multiple binary logistic regression or the multivariable logistic regression. Here, we expand our model and include two or more independent variables (covariates). This is a adjusted model and we can obtain the estimate of a particular covariate independent of the other covariates in the model.</li>
</ol>
</div>
<div id="simple-binary-logistic-regression" class="section level2" number="9.8">
<h2><span class="header-section-number">9.8</span> Simple binary logistic regression</h2>
<p>The simple binary logistic regression has a dependent variable and only one independent (covariate) variable. in our dataset, for example, we can have</p>
<ol style="list-style-type: decimal">
<li>status as the dependent variable.</li>
<li>gcs as the independent variable.</li>
</ol>
<p>The independent variable can be a numerical or a categorical variable. To estimate the log odds (the regression parameters, <span class="math inline">\(\beta\)</span>) for the covariate Glasgow Coma Scale (GCS), we can write the logit model as:</p>
<p><span class="math display">\[log\frac{p(status = dead)}{1 - p(status = dead)}  = \hat\beta_0 + \hat\beta_1(gcs)\]</span></p>
<p>In R, we use the <code>glm()</code> function to estimate the regression parameters and other parameters of interest. Let’s run the model with gcs as the covariate and name the model as <code>fatal_glm_1</code></p>
<div class="sourceCode" id="cb348"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb348-1"><a href="binary-logistic-regression.html#cb348-1" aria-hidden="true" tabindex="-1"></a>fatal_glm_1 <span class="ot">&lt;-</span> </span>
<span id="cb348-2"><a href="binary-logistic-regression.html#cb348-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">glm</span>(status <span class="sc">~</span> gcs, </span>
<span id="cb348-3"><a href="binary-logistic-regression.html#cb348-3" aria-hidden="true" tabindex="-1"></a>      <span class="at">data =</span> fatal, </span>
<span id="cb348-4"><a href="binary-logistic-regression.html#cb348-4" aria-hidden="true" tabindex="-1"></a>      <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">&#39;logit&#39;</span>))</span></code></pre></div>
<p>To get the summarized result of the model, we will use the <code>summary()</code> function:</p>
<div class="sourceCode" id="cb349"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb349-1"><a href="binary-logistic-regression.html#cb349-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fatal_glm_1)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = status ~ gcs, family = binomial(link = &quot;logit&quot;), 
##     data = fatal)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -2.1179  -0.3921  -0.3921  -0.3921   2.2820  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)  3.29479    0.60432   5.452 4.98e-08 ***
## gcs         -0.38811    0.05213  -7.446 9.64e-14 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 250.83  on 225  degrees of freedom
## Residual deviance: 170.92  on 224  degrees of freedom
## AIC: 174.92
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<p>To get the model summary in a data frame format, so we can edit more easily, we can use the <code>tidy()</code> function from the <strong>broom</strong> package. The package also contains other functions to provide other parameters useful for us later.</p>
<p>The function <code>conf.int()</code> will provide the confidence intervals (CI). The default is set at the <span class="math inline">\(95%\)</span> level:</p>
<div class="sourceCode" id="cb351"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb351-1"><a href="binary-logistic-regression.html#cb351-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(fatal_glm_1, <span class="at">conf.int =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## # A tibble: 2 x 7
##   term        estimate std.error statistic  p.value conf.low conf.high
##   &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
## 1 (Intercept)    3.29     0.604       5.45 4.98e- 8    2.17      4.55 
## 2 gcs           -0.388    0.0521     -7.45 9.64e-14   -0.497    -0.292</code></pre>
<p>The estimates here are the log odds for death for a given value of gcs. In this example, each unit increase in gcs, the crude or unadjusted log odds for death due to stroke change by a factor <span class="math inline">\(-0.388\)</span> with <span class="math inline">\(95%\)</span> CI ranges from <span class="math inline">\(-0.497 and -0.292\)</span>.</p>
<p>Now, let’s use another covariate, <code>stroke_type</code>. Stroke type has 2 levels or categories; Haemorrhagic Stroke (HS) and Ischaemic Stroke (IS). HS is known to cause higher risk for deaths in stroke. We will model stroke type (<code>stroke_type</code>), name the model as <code>fatal_glm_2</code> and show the result using <code>tidy()</code></p>
<div class="sourceCode" id="cb353"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb353-1"><a href="binary-logistic-regression.html#cb353-1" aria-hidden="true" tabindex="-1"></a>fatal_glm_2 <span class="ot">&lt;-</span> </span>
<span id="cb353-2"><a href="binary-logistic-regression.html#cb353-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">glm</span>(status <span class="sc">~</span> stroke_type, </span>
<span id="cb353-3"><a href="binary-logistic-regression.html#cb353-3" aria-hidden="true" tabindex="-1"></a>      <span class="at">data =</span> fatal, </span>
<span id="cb353-4"><a href="binary-logistic-regression.html#cb353-4" aria-hidden="true" tabindex="-1"></a>      <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">&#39;logit&#39;</span>))</span>
<span id="cb353-5"><a href="binary-logistic-regression.html#cb353-5" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(fatal_glm_2, <span class="at">conf.int =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## # A tibble: 2 x 7
##   term                  estimate std.error statistic  p.value conf.low conf.high
##   &lt;chr&gt;                    &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
## 1 (Intercept)              -2.05     0.258     -7.95 1.80e-15    -2.59     -1.57
## 2 stroke_typeHaemorrha~     2.02     0.344      5.88 4.05e- 9     1.36      2.72</code></pre>
<p>It seems that patients with Haemorrhagic Stroke (HS) had higher log odds for death during admission - by a factor <span class="math inline">\(2.02\)</span> - than patients with Ischaemic Stroke (IS).</p>
</div>
<div id="multiple-binary-logistic-regression" class="section level2" number="9.9">
<h2><span class="header-section-number">9.9</span> Multiple binary logistic regression</h2>
<p>The is strong motivation to include other covariates in the model. This is because</p>
<ul>
<li>It is unlikely that only one variable (gcs or stroke type) that is related with stroke. For example, cardiovascular disease has many factors that affect the outcome. So, it makes more sense to consider adding other seemingly important independent variable in the model.</li>
<li>by adding more covariates in the model, we can estimate the adjusted log odds. These are the log odds of a particular covariate independent of other covariates.</li>
<li>we can add other covariate to adjust for the confounding effects</li>
<li>interaction (the product of two covariates) can also be estimated</li>
</ul>
<p>To add or not to add variables is a big subject on its own. Usually it is governed by clinical experience, subject matter experts and some preliminary analysis.</p>
<p>Let’s expand our model and include gcs, stroke type, sex, dm, sbp and age in the model. We will name this model as <code>fatal_mv</code>. To run this model and get the estimates in R:</p>
<div class="sourceCode" id="cb355"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb355-1"><a href="binary-logistic-regression.html#cb355-1" aria-hidden="true" tabindex="-1"></a>fatal_mv1 <span class="ot">&lt;-</span> </span>
<span id="cb355-2"><a href="binary-logistic-regression.html#cb355-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">glm</span>(status <span class="sc">~</span> gcs <span class="sc">+</span> stroke_type <span class="sc">+</span> sex <span class="sc">+</span> dm <span class="sc">+</span> sbp <span class="sc">+</span> age, </span>
<span id="cb355-3"><a href="binary-logistic-regression.html#cb355-3" aria-hidden="true" tabindex="-1"></a>      <span class="at">data =</span> fatal, </span>
<span id="cb355-4"><a href="binary-logistic-regression.html#cb355-4" aria-hidden="true" tabindex="-1"></a>      <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">&#39;logit&#39;</span>))</span>
<span id="cb355-5"><a href="binary-logistic-regression.html#cb355-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb355-6"><a href="binary-logistic-regression.html#cb355-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fatal_mv1)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = status ~ gcs + stroke_type + sex + dm + sbp + age, 
##     family = binomial(link = &quot;logit&quot;), data = fatal)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -2.3715  -0.4687  -0.3280  -0.1921   2.5150  
## 
## Coefficients:
##                           Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)             -0.1588269  1.6174965  -0.098  0.92178    
## gcs                     -0.3284640  0.0557574  -5.891 3.84e-09 ***
## stroke_typeHaemorrhagic  1.2662764  0.4365882   2.900  0.00373 ** 
## sexfemale                0.4302901  0.4362742   0.986  0.32399    
## dmyes                    0.4736670  0.4362309   1.086  0.27756    
## sbp                      0.0008612  0.0060619   0.142  0.88703    
## age                      0.0242321  0.0154010   1.573  0.11562    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 250.83  on 225  degrees of freedom
## Residual deviance: 159.34  on 219  degrees of freedom
## AIC: 173.34
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<p>We could get a cleaner result in a data frame format (and you can edit in spreadsheet easily) by using <code>tidy()</code>:</p>
<div class="sourceCode" id="cb357"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb357-1"><a href="binary-logistic-regression.html#cb357-1" aria-hidden="true" tabindex="-1"></a>log_odds <span class="ot">&lt;-</span> <span class="fu">tidy</span>(fatal_mv1, </span>
<span id="cb357-2"><a href="binary-logistic-regression.html#cb357-2" aria-hidden="true" tabindex="-1"></a>                 <span class="at">conf.int =</span> <span class="cn">TRUE</span>)</span>
<span id="cb357-3"><a href="binary-logistic-regression.html#cb357-3" aria-hidden="true" tabindex="-1"></a>log_odds</span></code></pre></div>
<pre><code>## # A tibble: 7 x 7
##   term               estimate std.error statistic     p.value conf.low conf.high
##   &lt;chr&gt;                 &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;       &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
## 1 (Intercept)        -1.59e-1   1.62      -0.0982     9.22e-1 -3.38       3.01  
## 2 gcs                -3.28e-1   0.0558    -5.89       3.84e-9 -0.444     -0.224 
## 3 stroke_typeHaemor~  1.27e+0   0.437      2.90       3.73e-3  0.411      2.13  
## 4 sexfemale           4.30e-1   0.436      0.986      3.24e-1 -0.420      1.30  
## 5 dmyes               4.74e-1   0.436      1.09       2.78e-1 -0.368      1.35  
## 6 sbp                 8.61e-4   0.00606    0.142      8.87e-1 -0.0110     0.0129
## 7 age                 2.42e-2   0.0154     1.57       1.16e-1 -0.00520    0.0555</code></pre>
<p>We could see in the multivariable model, that</p>
<ul>
<li>with one unit increase in Glasgow Coma Scale (GCS), the log odds for death during hospitalization equals to <span class="math inline">\(-0.328\)</span>, adjusting for other covariates</li>
<li>patients with HS has <span class="math inline">\(1.266\)</span> times the log odds for death as compared to patients with IS, adjusting for other covariates.</li>
<li>female patients have <span class="math inline">\(0.430\)</span> times the log odds for death as compared to male patients, adjusting for other covariates</li>
<li>patients with diabetes mellitus had <span class="math inline">\(0.474\)</span> times the log odds for deaths as compared to patients with no diabetes mellitus</li>
<li>With one mmHg increase in systolic blood pressure, the log odds for deaths change by a factor of <span class="math inline">\(0.00086\)</span>, when adjusting for other variables.<br />
</li>
<li>with an increase in one year of age, the log odds for deaths change by a factor of <span class="math inline">\(0.024\)</span>, when adjusting for other variables.</li>
</ul>
</div>
<div id="convert-the-log-odds-to-odds-ratio" class="section level2" number="9.10">
<h2><span class="header-section-number">9.10</span> Convert the log odds to odds ratio</h2>
<p>For lay person, it is difficult to interpret the log odds. It is easier to interpret using the odds ratio. To do this, we can use the argument <code>exponentiate = TRUE</code> in the <code>tidy()</code> function. However, we also know that the odds ratio can be easily calculate by <span class="math inline">\(\exp^{\beta_i}\)</span></p>
<div class="sourceCode" id="cb359"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb359-1"><a href="binary-logistic-regression.html#cb359-1" aria-hidden="true" tabindex="-1"></a>odds_ratio <span class="ot">&lt;-</span> <span class="fu">tidy</span>(fatal_mv1,</span>
<span id="cb359-2"><a href="binary-logistic-regression.html#cb359-2" aria-hidden="true" tabindex="-1"></a>                   <span class="at">exponentiate =</span> <span class="cn">TRUE</span>,  </span>
<span id="cb359-3"><a href="binary-logistic-regression.html#cb359-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">conf.int =</span> <span class="cn">TRUE</span>)</span>
<span id="cb359-4"><a href="binary-logistic-regression.html#cb359-4" aria-hidden="true" tabindex="-1"></a>odds_ratio</span></code></pre></div>
<pre><code>## # A tibble: 7 x 7
##   term               estimate std.error statistic     p.value conf.low conf.high
##   &lt;chr&gt;                 &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;       &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
## 1 (Intercept)           0.853   1.62      -0.0982     9.22e-1   0.0341    20.3  
## 2 gcs                   0.720   0.0558    -5.89       3.84e-9   0.641      0.799
## 3 stroke_typeHaemor~    3.55    0.437      2.90       3.73e-3   1.51       8.45 
## 4 sexfemale             1.54    0.436      0.986      3.24e-1   0.657      3.69 
## 5 dmyes                 1.61    0.436      1.09       2.78e-1   0.692      3.87 
## 6 sbp                   1.00    0.00606    0.142      8.87e-1   0.989      1.01 
## 7 age                   1.02    0.0154     1.57       1.16e-1   0.995      1.06</code></pre>
</div>
<div id="making-inference" class="section level2" number="9.11">
<h2><span class="header-section-number">9.11</span> Making inference</h2>
<p>Let us combine the results from the log odds and the odds ratio and rename the table properly.</p>
<div class="sourceCode" id="cb361"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb361-1"><a href="binary-logistic-regression.html#cb361-1" aria-hidden="true" tabindex="-1"></a>tab_logistic <span class="ot">&lt;-</span> <span class="fu">bind_cols</span>(log_odds, odds_ratio) </span></code></pre></div>
<pre><code>## New names:
## * term -&gt; term...1
## * estimate -&gt; estimate...2
## * std.error -&gt; std.error...3
## * statistic -&gt; statistic...4
## * p.value -&gt; p.value...5
## * ...</code></pre>
<div class="sourceCode" id="cb363"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb363-1"><a href="binary-logistic-regression.html#cb363-1" aria-hidden="true" tabindex="-1"></a>tab_logistic <span class="sc">%&gt;%</span> </span>
<span id="cb363-2"><a href="binary-logistic-regression.html#cb363-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(term...<span class="dv">1</span>, estimate...<span class="dv">2</span>, std.error...<span class="dv">3</span>, </span>
<span id="cb363-3"><a href="binary-logistic-regression.html#cb363-3" aria-hidden="true" tabindex="-1"></a>         estimate...<span class="dv">9</span>, conf.low...<span class="dv">13</span>, conf.high...<span class="dv">14</span> ,p.value...<span class="dv">5</span>) <span class="sc">%&gt;%</span></span>
<span id="cb363-4"><a href="binary-logistic-regression.html#cb363-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">covariate =</span> term...<span class="dv">1</span>, </span>
<span id="cb363-5"><a href="binary-logistic-regression.html#cb363-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">log_odds =</span> estimate...<span class="dv">2</span>,</span>
<span id="cb363-6"><a href="binary-logistic-regression.html#cb363-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">SE =</span> std.error...<span class="dv">3</span>,</span>
<span id="cb363-7"><a href="binary-logistic-regression.html#cb363-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">odds_ratio =</span> estimate...<span class="dv">9</span>,</span>
<span id="cb363-8"><a href="binary-logistic-regression.html#cb363-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">lower_OR =</span> conf.low...<span class="dv">13</span>, </span>
<span id="cb363-9"><a href="binary-logistic-regression.html#cb363-9" aria-hidden="true" tabindex="-1"></a>         <span class="at">upper_OR =</span> conf.high...<span class="dv">14</span>,</span>
<span id="cb363-10"><a href="binary-logistic-regression.html#cb363-10" aria-hidden="true" tabindex="-1"></a>         <span class="at">p.val =</span> p.value...<span class="dv">5</span>) </span></code></pre></div>
<pre><code>## # A tibble: 7 x 7
##   covariate                log_odds      SE odds_ratio lower_OR upper_OR   p.val
##   &lt;chr&gt;                       &lt;dbl&gt;   &lt;dbl&gt;      &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt;
## 1 (Intercept)             -0.159    1.62         0.853   0.0341   20.3   9.22e-1
## 2 gcs                     -0.328    0.0558       0.720   0.641     0.799 3.84e-9
## 3 stroke_typeHaemorrhagic  1.27     0.437        3.55    1.51      8.45  3.73e-3
## 4 sexfemale                0.430    0.436        1.54    0.657     3.69  3.24e-1
## 5 dmyes                    0.474    0.436        1.61    0.692     3.87  2.78e-1
## 6 sbp                      0.000861 0.00606      1.00    0.989     1.01  8.87e-1
## 7 age                      0.0242   0.0154       1.02    0.995     1.06  1.16e-1</code></pre>
<p>In the model, it means that:</p>
<ul>
<li>if <strong>gcs</strong> increases by 1 unit (when <em>stroke type</em> is adjusted), the log odds for death changes by a factor <span class="math inline">\(-0.32\)</span> or the odds for death changes by a factor <span class="math inline">\(0.72\)</span> (odds for death reduces for <span class="math inline">\(28\%\)</span>). The the <span class="math inline">\(95\%CI\)</span> are between <span class="math inline">\(21\%,36\%\)</span>, adjusting for other covariates.</li>
<li>patients with HS has <span class="math inline">\(3.55\%\)</span> times higher odds for stroke deaths - with <span class="math inline">\(95\%CI : 17\%, 85\%\)</span> - as compared to patients with HS, adjusting for other independent variables.</li>
<li>female patients have <span class="math inline">\(53\%\)</span> higher odds for death as compared to female patients (<span class="math inline">\(p = 0.154\)</span>), adjusting for other covariates</li>
<li>patients with diabetes mellitus had <span class="math inline">\(60.6\%\)</span> higher odds for deaths compared to patients with no diabetes mellitus though the p value is above <span class="math inline">\(5\%\)</span> (<span class="math inline">\(p = 0.642\%\)</span>)</li>
<li>With one mmHg increase in systolic blood pressure, the odds for death change by a factor <span class="math inline">\(1.00086\)</span>, when adjusting for other variables. The p value is also larger than <span class="math inline">\(5\%\)</span>.<br />
</li>
<li>with an increase in one year of age, the odds for deaths increase by a factor of <span class="math inline">\(1.025\)</span>, when adjusting for other variables. However, the p value is <span class="math inline">\(0.115\)</span></li>
</ul>
</div>
<div id="model-comparison" class="section level2" number="9.12">
<h2><span class="header-section-number">9.12</span> Model comparison</h2>
<p>It is not advisable to assess the important of variables based on their p-values or the Wald statistics. The better way is to use likelihood ratio to compare models and assess the importance of variables.</p>
<p>For example, is there any statistical difference between model 1 (<code>fatal_mv</code>) and model 2 (<code>fatal_glm_1</code>) if we set the level of significance at <span class="math inline">\(5\%\)</span>?</p>
<div class="sourceCode" id="cb365"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb365-1"><a href="binary-logistic-regression.html#cb365-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>( fatal_glm_1, fatal_mv1, <span class="at">test =</span> <span class="st">&#39;Chisq&#39;</span>)</span></code></pre></div>
<pre><code>## Analysis of Deviance Table
## 
## Model 1: status ~ gcs
## Model 2: status ~ gcs + stroke_type + sex + dm + sbp + age
##   Resid. Df Resid. Dev Df Deviance Pr(&gt;Chi)  
## 1       224     170.92                       
## 2       219     159.34  5   11.582  0.04098 *
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Both models are different statistically (at <span class="math inline">\(5\%\)</span> level). Hence, we prefer to keep model <code>fatal_mv1</code>.</p>
<p>Now let’s be economical, and just keep gcs, stroke type and age in the model. And let’s name this model as <code>fatal_mv2</code></p>
<div class="sourceCode" id="cb367"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb367-1"><a href="binary-logistic-regression.html#cb367-1" aria-hidden="true" tabindex="-1"></a>fatal_mv2 <span class="ot">&lt;-</span> </span>
<span id="cb367-2"><a href="binary-logistic-regression.html#cb367-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">glm</span>(status <span class="sc">~</span> gcs <span class="sc">+</span> stroke_type <span class="sc">+</span> age, </span>
<span id="cb367-3"><a href="binary-logistic-regression.html#cb367-3" aria-hidden="true" tabindex="-1"></a>      <span class="at">data =</span> fatal,</span>
<span id="cb367-4"><a href="binary-logistic-regression.html#cb367-4" aria-hidden="true" tabindex="-1"></a>      <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">&#39;logit&#39;</span>))</span></code></pre></div>
<p>And perform model comparison again</p>
<div class="sourceCode" id="cb368"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb368-1"><a href="binary-logistic-regression.html#cb368-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>( fatal_mv1, </span>
<span id="cb368-2"><a href="binary-logistic-regression.html#cb368-2" aria-hidden="true" tabindex="-1"></a>       fatal_mv2, <span class="at">test =</span> <span class="st">&#39;Chisq&#39;</span>)</span></code></pre></div>
<pre><code>## Analysis of Deviance Table
## 
## Model 1: status ~ gcs + stroke_type + sex + dm + sbp + age
## Model 2: status ~ gcs + stroke_type + age
##   Resid. Df Resid. Dev Df Deviance Pr(&gt;Chi)
## 1       219     159.34                     
## 2       222     161.51 -3  -2.1743    0.537</code></pre>
<p>The p-value is above the threshold of <span class="math inline">\(5\%\)</span>, so we can not reject the null hypothesis that say both models are not statistically different. So by obeying the Occam’s razor principle, we will choose a simpler model that is model <code>fatal_mv2</code> for further exploration.</p>
</div>
<div id="adding-an-interaction-term" class="section level2" number="9.13">
<h2><span class="header-section-number">9.13</span> Adding an interaction term</h2>
<p>Interaction effects occur when the effect of one variable depends on the value of another variable. Interaction effects are common in regression analysis, ANOVA, and designed experiments.</p>
<p>Interaction involves two risk factors (and their effect on one disease outcome). If the effect of one risk factor is the same within strata defined by the other, then there is NO interaction. When the effect of one risk factor is different within strata defined by the other, then there is an interaction (biological)</p>
<p>(Statistical) interaction can be measured based on the ways that risks are calculated (modeling). The presence of interaction based on measurements is called statistical interaction, and inherently it may not reflect the true biological interaction.</p>
<p>Let’s add an interaction between stroke type and diabetes:</p>
<div class="sourceCode" id="cb370"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb370-1"><a href="binary-logistic-regression.html#cb370-1" aria-hidden="true" tabindex="-1"></a>fatal_mv2_ia <span class="ot">&lt;-</span> </span>
<span id="cb370-2"><a href="binary-logistic-regression.html#cb370-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">glm</span>(status <span class="sc">~</span> gcs <span class="sc">+</span> stroke_type <span class="sc">+</span> stroke_type<span class="sc">:</span>gcs <span class="sc">+</span> age, </span>
<span id="cb370-3"><a href="binary-logistic-regression.html#cb370-3" aria-hidden="true" tabindex="-1"></a>      <span class="at">data =</span> fatal, </span>
<span id="cb370-4"><a href="binary-logistic-regression.html#cb370-4" aria-hidden="true" tabindex="-1"></a>      <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">&#39;logit&#39;</span>))</span>
<span id="cb370-5"><a href="binary-logistic-regression.html#cb370-5" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(fatal_mv2_ia)</span></code></pre></div>
<pre><code>## # A tibble: 5 x 5
##   term                        estimate std.error statistic   p.value
##   &lt;chr&gt;                          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
## 1 (Intercept)                   0.508     1.37       0.371 0.710    
## 2 gcs                          -0.320     0.0800    -4.01  0.0000619
## 3 stroke_typeHaemorrhagic       1.61      1.30       1.24  0.217    
## 4 age                           0.0236    0.0147     1.60  0.109    
## 5 gcs:stroke_typeHaemorrhagic  -0.0347    0.111     -0.312 0.755</code></pre>
<p><span class="math display">\[\hat{g}(x)  = \hat\beta_0 + \hat\beta_1(gcs) + \hat\beta_2(stroke type) + \hat\beta_3(age)+ \hat\beta_4(gcs \times stroke_type)\]</span></p>
<p>To decide if an interaction term should stay in the model, we suggest you to consider the biological and statistical significance. If you think the interaction justifies both reasons, then it is preferred you keep the interaction term in the model. For example, for our model:</p>
<ul>
<li>the coefficient for the interaction term for stroke type and gcs is not significant at %5%$ level.</li>
<li>after getting further advice from the stroke experts, we believe that the effect of gcs on stroke death is not largely different between different stroke type</li>
</ul>
<p>And because of both reasons, we have decided not to keep the interaction for gcs and stroke type in the model.</p>
</div>
<div id="prediction-from-binary-logistic-regression" class="section level2" number="9.14">
<h2><span class="header-section-number">9.14</span> Prediction from binary logistic regression</h2>
<p>We can use the <code>broom::augment()</code> function to calculate the</p>
<ol style="list-style-type: decimal">
<li>log odds</li>
<li>probability</li>
<li>residuals</li>
<li>hat values</li>
<li>Cooks distance</li>
<li>standardized residuals</li>
</ol>
<div id="predict-the-log-odds" class="section level3" number="9.14.1">
<h3><span class="header-section-number">9.14.1</span> Predict the log odds</h3>
<p>To obtain the <code>.fitted</code> column (representing the estimated log odds for death) for each patient, we can run:</p>
<div class="sourceCode" id="cb372"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb372-1"><a href="binary-logistic-regression.html#cb372-1" aria-hidden="true" tabindex="-1"></a>log_odds_mv2 <span class="ot">&lt;-</span> <span class="fu">augment</span>(fatal_mv2)</span>
<span id="cb372-2"><a href="binary-logistic-regression.html#cb372-2" aria-hidden="true" tabindex="-1"></a>log_odds_mv2 <span class="sc">%&gt;%</span></span>
<span id="cb372-3"><a href="binary-logistic-regression.html#cb372-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>)</span></code></pre></div>
<pre><code>## # A tibble: 10 x 10
##    status   gcs stroke_type        age .fitted .resid .std.resid    .hat .sigma
##    &lt;fct&gt;  &lt;dbl&gt; &lt;fct&gt;            &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;      &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;
##  1 alive     13 Ischaemic Stroke    50   -2.49 -0.398     -0.400 0.00991  0.854
##  2 alive     15 Ischaemic Stroke    58   -2.98 -0.314     -0.315 0.00584  0.855
##  3 alive     15 Ischaemic Stroke    64   -2.84 -0.337     -0.338 0.00590  0.855
##  4 alive     15 Ischaemic Stroke    50   -3.17 -0.287     -0.288 0.00657  0.855
##  5 alive     15 Ischaemic Stroke    65   -2.82 -0.341     -0.342 0.00599  0.855
##  6 alive     15 Ischaemic Stroke    78   -2.51 -0.395     -0.397 0.00980  0.854
##  7 dead      13 Ischaemic Stroke    66   -2.12  2.11       2.12  0.00831  0.843
##  8 alive     15 Ischaemic Stroke    72   -2.65 -0.369     -0.370 0.00731  0.855
##  9 alive     15 Ischaemic Stroke    61   -2.91 -0.325     -0.326 0.00579  0.855
## 10 dead      10 Ischaemic Stroke    64   -1.15  1.69       1.70  0.0173   0.847
## # ... with 1 more variable: .cooksd &lt;dbl&gt;</code></pre>
<p>The <code>slice()</code> gives the snapshot of the data. In this case, we choose the first 10 patients.</p>
</div>
<div id="predict-the-probabilities" class="section level3" number="9.14.2">
<h3><span class="header-section-number">9.14.2</span> Predict the probabilities</h3>
<p>To obtain the <code>.fitted</code> column (representing the estimated probabilities for death) for each patient, we can run:</p>
<div class="sourceCode" id="cb374"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb374-1"><a href="binary-logistic-regression.html#cb374-1" aria-hidden="true" tabindex="-1"></a>prob_mv2 <span class="ot">&lt;-</span> </span>
<span id="cb374-2"><a href="binary-logistic-regression.html#cb374-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">augment</span>(fatal_mv2, </span>
<span id="cb374-3"><a href="binary-logistic-regression.html#cb374-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">type.predict =</span> <span class="st">&quot;response&quot;</span>)</span>
<span id="cb374-4"><a href="binary-logistic-regression.html#cb374-4" aria-hidden="true" tabindex="-1"></a>prob_mv2 <span class="sc">%&gt;%</span></span>
<span id="cb374-5"><a href="binary-logistic-regression.html#cb374-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>)</span></code></pre></div>
<pre><code>## # A tibble: 10 x 10
##    status   gcs stroke_type        age .fitted .resid .std.resid    .hat .sigma
##    &lt;fct&gt;  &lt;dbl&gt; &lt;fct&gt;            &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;      &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;
##  1 alive     13 Ischaemic Stroke    50  0.0763 -0.398     -0.400 0.00991  0.854
##  2 alive     15 Ischaemic Stroke    58  0.0482 -0.314     -0.315 0.00584  0.855
##  3 alive     15 Ischaemic Stroke    64  0.0551 -0.337     -0.338 0.00590  0.855
##  4 alive     15 Ischaemic Stroke    50  0.0403 -0.287     -0.288 0.00657  0.855
##  5 alive     15 Ischaemic Stroke    65  0.0564 -0.341     -0.342 0.00599  0.855
##  6 alive     15 Ischaemic Stroke    78  0.0750 -0.395     -0.397 0.00980  0.854
##  7 dead      13 Ischaemic Stroke    66  0.107   2.11       2.12  0.00831  0.843
##  8 alive     15 Ischaemic Stroke    72  0.0658 -0.369     -0.370 0.00731  0.855
##  9 alive     15 Ischaemic Stroke    61  0.0516 -0.325     -0.326 0.00579  0.855
## 10 dead      10 Ischaemic Stroke    64  0.241   1.69       1.70  0.0173   0.847
## # ... with 1 more variable: .cooksd &lt;dbl&gt;</code></pre>
</div>
</div>
<div id="model-fitness" class="section level2" number="9.15">
<h2><span class="header-section-number">9.15</span> Model fitness</h2>
<p>We will assess the overall model fitness by checking the</p>
<ul>
<li>the area under the curve</li>
<li>the Hosmer-Lemeshow test</li>
<li>the modidied Hosmer-Lemeshow test</li>
<li>the Oseo Rojek test</li>
</ul>
<p>The p-values of bigger than 0.05 indicates that there is no significant difference between the observed data and the predicted data (from our model). That supports the good fit of the model.</p>
<div class="sourceCode" id="cb376"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb376-1"><a href="binary-logistic-regression.html#cb376-1" aria-hidden="true" tabindex="-1"></a>fit_m <span class="ot">&lt;-</span> <span class="fu">gof</span>(fatal_mv2, </span>
<span id="cb376-2"><a href="binary-logistic-regression.html#cb376-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">g =</span> <span class="dv">8</span>)</span></code></pre></div>
<pre><code>## Setting levels: control = 0, case = 1</code></pre>
<pre><code>## Setting direction: controls &lt; cases</code></pre>
<p><img src="08_logistic_2_files/figure-html/unnamed-chunk-21-1.png" width="672" />
The area under the curve is <span class="math inline">\(87.2\%\)</span>. The values of above 80 are considered to have good discriminating effect.</p>
<div class="sourceCode" id="cb379"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb379-1"><a href="binary-logistic-regression.html#cb379-1" aria-hidden="true" tabindex="-1"></a>fit_m<span class="sc">$</span>gof</span></code></pre></div>
<pre><code>##          test  stat       val df      pVal
## 1:         HL chiSq  4.622183  6 0.5930997
## 2:        mHL     F  1.071882  7 0.3844230
## 3:       OsRo     Z -0.501724 NA 0.6158617
## 4: SstPgeq0.5     Z  1.348843 NA 0.1773873
## 5:   SstPl0.5     Z  1.516578 NA 0.1293733
## 6:    SstBoth chiSq  4.119387  2 0.1274931
## 7: SllPgeq0.5 chiSq  1.579811  1 0.2087879
## 8:   SllPl0.5 chiSq  2.311910  1 0.1283862
## 9:    SllBoth chiSq  2.341198  2 0.3101811</code></pre>
<p>The Hosmer Lemeshow, modified Hosmer Lemeshow and Oseo Rojek are all above <span class="math inline">\(5\%\)</span> values which are supportive of good fit of the model.</p>
</div>
<div id="presentation" class="section level2" number="9.16">
<h2><span class="header-section-number">9.16</span> Presentation</h2>
<p>The <strong>gtsummary</strong> package has a useful function <code>tbld_regression()</code> to produce a formatted table suitable for publication.</p>
<p>This is the table for adjusted log odds ratio:</p>
<div class="sourceCode" id="cb381"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb381-1"><a href="binary-logistic-regression.html#cb381-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tbl_regression</span>(fatal_mv2)</span></code></pre></div>
<div id="coxtqcdgqq" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#coxtqcdgqq .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#coxtqcdgqq .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#coxtqcdgqq .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#coxtqcdgqq .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 6px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#coxtqcdgqq .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#coxtqcdgqq .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#coxtqcdgqq .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#coxtqcdgqq .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#coxtqcdgqq .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#coxtqcdgqq .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#coxtqcdgqq .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#coxtqcdgqq .gt_group_heading {
  padding: 8px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#coxtqcdgqq .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#coxtqcdgqq .gt_from_md > :first-child {
  margin-top: 0;
}

#coxtqcdgqq .gt_from_md > :last-child {
  margin-bottom: 0;
}

#coxtqcdgqq .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#coxtqcdgqq .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 12px;
}

#coxtqcdgqq .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#coxtqcdgqq .gt_first_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
}

#coxtqcdgqq .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#coxtqcdgqq .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#coxtqcdgqq .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#coxtqcdgqq .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#coxtqcdgqq .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#coxtqcdgqq .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding: 4px;
}

#coxtqcdgqq .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#coxtqcdgqq .gt_sourcenote {
  font-size: 90%;
  padding: 4px;
}

#coxtqcdgqq .gt_left {
  text-align: left;
}

#coxtqcdgqq .gt_center {
  text-align: center;
}

#coxtqcdgqq .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#coxtqcdgqq .gt_font_normal {
  font-weight: normal;
}

#coxtqcdgqq .gt_font_bold {
  font-weight: bold;
}

#coxtqcdgqq .gt_font_italic {
  font-style: italic;
}

#coxtqcdgqq .gt_super {
  font-size: 65%;
}

#coxtqcdgqq .gt_footnote_marks {
  font-style: italic;
  font-weight: normal;
  font-size: 65%;
}
</style>
<table class="gt_table">
  
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1"><strong>Characteristic</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>log(OR)</strong><sup class="gt_footnote_marks">1</sup></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>95% CI</strong><sup class="gt_footnote_marks">1</sup></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>p-value</strong></th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td class="gt_row gt_left">earliest Glasgow Coma Scale</td>
<td class="gt_row gt_center">-0.34</td>
<td class="gt_row gt_center">-0.45, -0.24</td>
<td class="gt_row gt_center"><0.001</td></tr>
    <tr><td class="gt_row gt_left">Ischaemic Stroke or Haemorrhagic</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">Ischaemic Stroke</td>
<td class="gt_row gt_center">—</td>
<td class="gt_row gt_center">—</td>
<td class="gt_row gt_center"></td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">Haemorrhagic</td>
<td class="gt_row gt_center">1.2</td>
<td class="gt_row gt_center">0.38, 2.1</td>
<td class="gt_row gt_center">0.004</td></tr>
    <tr><td class="gt_row gt_left">age in years</td>
<td class="gt_row gt_center">0.02</td>
<td class="gt_row gt_center">0.00, 0.05</td>
<td class="gt_row gt_center">0.11</td></tr>
  </tbody>
  
  <tfoot>
    <tr class="gt_footnotes">
      <td colspan="4">
        <p class="gt_footnote">
          <sup class="gt_footnote_marks">
            <em>1</em>
          </sup>
           
          OR = Odds Ratio, CI = Confidence Interval
          <br />
        </p>
      </td>
    </tr>
  </tfoot>
</table>
</div>
<p>And this is the table for adjusted odds ratio:</p>
<div class="sourceCode" id="cb382"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb382-1"><a href="binary-logistic-regression.html#cb382-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tbl_regression</span>(fatal_mv2, <span class="at">exponentiate =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<div id="lqqsiuikmm" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#lqqsiuikmm .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#lqqsiuikmm .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#lqqsiuikmm .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#lqqsiuikmm .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 6px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#lqqsiuikmm .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#lqqsiuikmm .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#lqqsiuikmm .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#lqqsiuikmm .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#lqqsiuikmm .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#lqqsiuikmm .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#lqqsiuikmm .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#lqqsiuikmm .gt_group_heading {
  padding: 8px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#lqqsiuikmm .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#lqqsiuikmm .gt_from_md > :first-child {
  margin-top: 0;
}

#lqqsiuikmm .gt_from_md > :last-child {
  margin-bottom: 0;
}

#lqqsiuikmm .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#lqqsiuikmm .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 12px;
}

#lqqsiuikmm .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#lqqsiuikmm .gt_first_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
}

#lqqsiuikmm .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#lqqsiuikmm .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#lqqsiuikmm .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#lqqsiuikmm .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#lqqsiuikmm .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#lqqsiuikmm .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding: 4px;
}

#lqqsiuikmm .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#lqqsiuikmm .gt_sourcenote {
  font-size: 90%;
  padding: 4px;
}

#lqqsiuikmm .gt_left {
  text-align: left;
}

#lqqsiuikmm .gt_center {
  text-align: center;
}

#lqqsiuikmm .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#lqqsiuikmm .gt_font_normal {
  font-weight: normal;
}

#lqqsiuikmm .gt_font_bold {
  font-weight: bold;
}

#lqqsiuikmm .gt_font_italic {
  font-style: italic;
}

#lqqsiuikmm .gt_super {
  font-size: 65%;
}

#lqqsiuikmm .gt_footnote_marks {
  font-style: italic;
  font-weight: normal;
  font-size: 65%;
}
</style>
<table class="gt_table">
  
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1"><strong>Characteristic</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>OR</strong><sup class="gt_footnote_marks">1</sup></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>95% CI</strong><sup class="gt_footnote_marks">1</sup></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>p-value</strong></th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td class="gt_row gt_left">earliest Glasgow Coma Scale</td>
<td class="gt_row gt_center">0.71</td>
<td class="gt_row gt_center">0.64, 0.79</td>
<td class="gt_row gt_center"><0.001</td></tr>
    <tr><td class="gt_row gt_left">Ischaemic Stroke or Haemorrhagic</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">Ischaemic Stroke</td>
<td class="gt_row gt_center">—</td>
<td class="gt_row gt_center">—</td>
<td class="gt_row gt_center"></td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">Haemorrhagic</td>
<td class="gt_row gt_center">3.40</td>
<td class="gt_row gt_center">1.46, 7.97</td>
<td class="gt_row gt_center">0.004</td></tr>
    <tr><td class="gt_row gt_left">age in years</td>
<td class="gt_row gt_center">1.02</td>
<td class="gt_row gt_center">1.00, 1.05</td>
<td class="gt_row gt_center">0.11</td></tr>
  </tbody>
  
  <tfoot>
    <tr class="gt_footnotes">
      <td colspan="4">
        <p class="gt_footnote">
          <sup class="gt_footnote_marks">
            <em>1</em>
          </sup>
           
          OR = Odds Ratio, CI = Confidence Interval
          <br />
        </p>
      </td>
    </tr>
  </tfoot>
</table>
</div>
</div>
<div id="references-1" class="section level2" number="9.17">
<h2><span class="header-section-number">9.17</span> References</h2>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="linear-regression.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="poisson-regression.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": false,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/drkamarul08_logistic_2.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["dataanalysis.pdf", "dataanalysis.epub", "dataanalysis.mobi"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "none"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
